### ISSUE TITLE
Loading models failing in python>=3.8 on Mac M1

### ISSUE THREAD

**Issue by ahalev** [sys-bio/roadrunner#1052]
`te.loada` and `te.loads` fail with:

`Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)`

on python 3.8, 3.9. 3.10. Does not fail with python=3.7. Happening on M1 (ARM64) mac.

Here is a simple example that illustrates the issue:

```python
import tellurium as te
rr = te.loada('''
    model wikipedia_example
      A + B -> C; k1*A+k2*B
      A = 1
      B = 2
      C = 0
      k1 = 0.1
      k2 = 0.2
    end
''') # fails on python>=3.8
```

May be related to [this issue](https://github.com/sys-bio/temp-biomodels/issues/137).

**Comment by luciansmith** [comment]
We don't have automatic builds set up for the M1 machine right now (no VM on Azure yet), so I've been building those releases by hand.  I have created a new release since this issue was filed, so it's worth trying again, though I didn't change anything to specifically address anything you brought up here.

If you pull the latest changes and still have the issue, can you tell me what OS version you have, and what version of roadrunner you have?  Thank you, and sorry for the late response.

**Comment by ahalev** [comment]
This works with python 3.8 and 3.10 with a clean install. Not sure what the issue was here but I'm going to go ahead and close this issue.

**Comment by luciansmith** [comment]
Glad it's now working, at any rate!
