### ISSUE TITLE
Redesign Integrator Interface

### ISSUE THREAD

**Issue by hsauro** [sys-bio/roadrunner#118]
The abstract integrator interface requires a developer to modify the base class when new integrators are added, this breaks encapsulation. In addition, properties of a given integrator are spread over a number of unrelated files. Only the integrator itself should be manage its properties. Currently when a new integrator is added additional changes may be required in unrelated parts of the libRoadRunner base. Integrators should be decoupled from the rest of the code base, currently that are not designed in a modular fashion. It should be possible to add new integrators without any changes to the basic libRoadRunner code base. The current implementation uses insufficient abstraction. 

Redesign the way new integrators are declared, added and used in libRoadRunner.

**Comment by 0u812** [comment]
Just adding some notes from conversation with @hsauro for future reference:
* Idea is to replace enum containing integrator types with alternate design:
 * Make integrator factory into singleton
 * Allow new integrators to be registered with singleton
 * Each integrator should handle its own tuning parameters (currently these are exposed in an unrelated file)

The enum needs to go because we have to modify the base class to change it. Next, we need a way of automatically registering integrators at startup somehow.

**Comment by 0u812** [comment]
Here's the best solution I can come up with: Let the registration function return a integer. For each integrator class (say CVODE in this example), declare some dummy global int:
```
// CVODEIntegrator.cpp

namespace rr {

class CVODEIntegrator : public Integrator {
public:
  CVODEIntegrator* makeNew() { return new CVODEIntegrator(); }
  ...
}

// Register the CVODE integrator and store the result in a global.
int cvode_regist = IntegratorFactory::Register("CVODE", CVODEIntegrator::makeNew);

} // namespace rr
```

It requires keeping around the global int which is not terribly elegant, but I think it's clear enough that someone in the future could understand how to add a new integrator. Thoughts?

**Comment by 0u812** [comment]
The alternative of course is to have a single function to register each integrator, which gets back to the problem of architecture non-extensibility.

**Comment by hsauro** [comment]
I'm ok with this solution.

**Comment by 0u812** [comment]
Refactor work completed by @wcopeland. Remaining task is to ensure that it passes the C/C++ & Python test suites.
