### ISSUE TITLE
No matching distribution found for libroadrunner

### ISSUE THREAD

**Issue by viktorashi** [sys-bio/roadrunner#1240]
Getting `ERROR: Could not find a version that satisfies the requirement libroadrunner (from versions: none)
ERROR: No matching distribution found for libroadrunner`

even if i'm trying to mention the version explicitily (==2.7.0 ,==2.2.1 etc.). I've tried installing pip + python 3.12 in a miniconda env and going about it the same way @efm46 did in #729 and apparently solved it like that but i'm still getting the same issue. 

It's kinda important to me cuz i'm trying to do my university thesis using tellurium which depends on roadrunner if i'm not mistaken and I stumbled across this issue while trying to do an editable install of tellurium, since i've found a little thingy that could be improved and i wanted to contribute to it

**Comment by viktorashi** [comment]
idk it works fine in a virtualenvwrapper env in which i've installed everything earlier but whenever i try creating a new one and installing it for that (either virtualenvwrapper or conda) i get the same issue.

**Comment by luciansmith** [comment]
I'm sorry things aren't working!  We can absolutely work to get things running again.  What MacOS version are you running?

**Comment by viktorashi** [comment]
Sonoma 14.5 (23F79)

**Comment by viktorashi** [comment]
also i was wondering, i found these conda packages `conda install sys-bio::roadrunner` and  `conda install sys-bio::tellurium` but they don't seem to be working. I'm guessing they both got discontinued since in your official docs you reccomend (to the people using conda) to just install tellurium using pip

**Comment by luciansmith** [comment]
Yeah, we've focused on just getting pip to work for several years now; the old conda packages are pretty out of date.

I looked at the pypi files, and there are indeed MacOS 14 / Python 3.12 wheel files there, but 'from versions: none' makes me think that for some reason, the installer thinks that they are incompatible.  If you don't mind, can you tell me what happens if you download the wheel file directly and try to install it?  The file is

https://files.pythonhosted.org/packages/60/67/49bfe2400b81a067a40f42d1e8e1b613979d2f3b4596ebd0445cdfcd5bcc/libroadrunner-2.7.0-cp312-cp312-macosx_14_0_arm64.whl

and you'd install it with 'pip install [name of file]'

It's possible that the architecture is incorrect, perhaps?

**Comment by viktorashi** [comment]
`ERROR: libroadrunner-2.7.0-cp312-cp312-macosx_14_0_arm64.whl is not a supported wheel on this platform.` unfortunately

running on an M1 Air if relevant

**Comment by luciansmith** [comment]
OK, that pinpoints the problem, at least:  that file is what pip has access too, so if it thinks it's not going to run, it won't try.  That means it doesn't matter if you have conda or pip, or if you have the right version of numpy: the problem is just finding something that works with your particular architecture.

So!  I thought all M1s were arm64, but it's possible yours is not:  can you check your 'About this mac' to see what it says for 'chip'?  c.f. https://docs.cse.lehigh.edu/determine-mac-architecture/

**Comment by viktorashi** [comment]
<img width="315" alt="image" src="https://github.com/user-attachments/assets/1be8f8f8-2ef0-4881-a06a-2960591874ce" />
i know for sure it's not an intel x86-64 bit. And i've had it for about 3 years frequently using arm64 only software and working fine

**Comment by viktorashi** [comment]
and `uname -a` returns
`Darwin vik.local 23.5.0 Darwin Kernel Version 23.5.0: Wed May  1 20:16:51 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T8103 arm64`

so yeah, but thanks SOOO much for responding so quick to everything and trying your best and being so active over heree!!

**Comment by viktorashi** [comment]
OMG I FOUND IT 
i tried installing every mac arm `.whl` from the latest release and this is the one that worked:
[libroadrunner-2.7.0-cp313-cp313-macosx_14_0_arm64.whl](https://github.com/sys-bio/roadrunner/releases/download/v2.7.0/libroadrunner-2.7.0-cp313-cp313-macosx_14_0_arm64.whl)

**Comment by viktorashi** [comment]
the only thing that seemed to differ from them is the number after `cp`. My very limited knowledge makes me think that's the version of the cpp compiler used? idk bruh i just think that's gotta be underlying problem

**Comment by luciansmith** [comment]
No, it's the version of python!  You were apparently using python 3.13, not 3.12.  And only the versions of python through 3.12 had been uploaded to pypi!  3.13 was only available relatively recently, so while the nightly builds had been updated to use it, we hadn't uploaded it to pypi yet.  I'm glad that it works now!

**Comment by viktorashi** [comment]
oh so i guess just downgrading python can solve many of my problems? 
what version do you recommend with which most packages (not only sys-bio adjescent) work by default without having to download the wheel of each? kinda 3.11 - 3.12 ish?

**Comment by hsauro** [comment]
I use 3.11 without any issues.

**Comment by viktorashi** [comment]
> I use 3.11 without any issues.

Damn man thanks a ton for all the help everybody, I just made a new conda env with python 3.11.9 and i was able to  `pip install -e .` on tellurium like a charm. Just wait to review my changes in a couple hours haha!!=))) thanks a ton everybodyy
