### ISSUE TITLE
Call to getNumberOfIntegrators (handle) only returns one integrator

### ISSUE THREAD

**Issue by hsauro** [sys-bio/roadrunner#154]
When a call is made to getNumberOfIntegrators (RRHandle handle), it returns one. However I know that the current libRoadRunner has at least three integrators available. 

getNumberOfIntegrators (RRHandle handle) should return the number of integrators supported by libRoadRunner which is currently three.

Note the following use case:

GUI application. User should be presented with a selection of integrators, currently there is no way to do this without the GUI having hardwired names of the supported integrators. We want to avoid hany hardwired names.

**Comment by wcopeland** [comment]
I am bringing @0u812 into this conversation.

As mentioned earlier (and in docs), *getNumberOfIntegrators(rrHandle)* returns the number of integrators that **exist within the current RoadRunner implementation**. By default, the "cvode" integrator is created a RoadRunner model is loaded. If you then call the method *setIntegrator("gillespie")*, for instance, and subsequently interrogate *getNumberOfIntegrators(rrHandle)* you will get a return value of two.

If the goal is to list all **possible** integrators, I think that should be a separate function. For example:

*getNumberOfIntegrators(rrHandle)* <-- Returns number of integrators in the current RoadRunner implementation.
*getNumberOfAcceptableIntegrators()* <-- Returns all possible integrators

Also, please note that **there appears to be no reason to pass a rrHandle to the second method**. The fact that a rrhandle was passed into the method led to me believe you preferred the former function behavior, because the information about all possible integrators does not and should not be held within a particular RoadRunner implementation. 

For example, the prior implementation used an *IntegratorFactory* class that hardwired the names of possible integrators into an enumeration and hardwired descriptions and hints into string arrays.

Anyway for now, I will move the IntegratorFactory implementation closer to the previous strategy of creating an enumeration that houses elements that correspond to all potential integrators. Additionally, I will make a helper function *IntegratorFactory::getNumberOfIntegrators()*.

*RoadRunner::getNumberOfIntegrators(rrHandle)* will return the number of integrators that existing in a specific RoadRunner implementation.
*IntegratorFactory::getNumberOfIntegrators()* will return the number of integrators registered within the factory. This in essence will tell how many integrators their are in total.

 @0u812 and I might want to spend next week seeing if there is a better solution?

**Comment by hsauro** [comment]
Do we need to know the number of instantiated integrators? In my use case I
think I only need to know what the current integrator is. What use case do
you have in mind where you need to know the number of *instantiated*
integrators?

What is absolutely critical for the GUI is knowing what kinds of
integrators are possible to bring on line. This means that if a new
libroadrunner is released with a new integrator, the GUI doesn't need to be
changed at all, it just asks what integrators what it supports, and lets
the user pick which one they want to use.

Herbert

**Comment by hsauro** [comment]
Are you suggesting going back to the original enumeration method for
listing integrators. Can't the individual integrators automatically
register themselves at start up and provide class methods for users to get
the name and description? That means everything is still kept within the
integrator class and now spread out to a factory. That way the integrators
don't have to be instantiated.

Herbert

**Comment by wcopeland** [comment]
That is a valid, and I can remove that functionality. But once again, are you fine with the idea of moving that method to the IntegratorFactory? It seems like it should belong there. 

Similarly, do you agree that there is no reason to pass the rrHandle to that method? That was what originally led me to change the function to instantiated integrators -- I tried to tailor the integrator refactor to the C API calls.

**Comment by wcopeland** [comment]
Currently all integrators provide class methods for users to get the name and description. Registering themselves is a little tricky, Kyle and I have spoken about this briefly in the past. Give me a chance to speak with him. We have envisioned a few solutions in the past.

**Comment by hsauro** [comment]
If you're calling class methods then there is not need to pass the
rrHandle. One question, if someone adds a new integrator, do they implement
a new integrator and then add update the factory?

This may be a limitation of C++, but is there anyway to get round that?

Herbert

**Comment by hsauro** [comment]
KEEP IT SIMPLE, KYLE DON"T MAKE IT COMPLICATED.

Caps on purpose :)

Herbert

**Comment by 0u812** [comment]
* Getting a list of available integrators: @wcopeland's idea of adding a method to the integrator factory for this sounds fine. The method can return a `vector<string>` of integrator names. In Python, I can make this a global function of the module:
```
import roadrunner
roadrunner.getIntegratorNames()
```
* Registering new integrators: You can register them on startup. In C++, you will have to store the result in a dummy int:
```
int cvode_regist = IntegratorFactory::Register("CVODE", CVODEIntegrator::makeNew);
```
More info: https://github.com/sys-bio/roadrunner/issues/118#issuecomment-95308302

**Comment by hsauro** [comment]
What about descriptions? I think that's all I need, after that when a user
selects an integrator its get set and all the other info become available.

H

**Comment by wcopeland** [comment]
**getIntegratorName()** and **getIntegratorDescription()** are methods that are enforced by the generic Integrator interface, so getting the description should not be a problem.

https://github.com/sys-bio/roadrunner/blob/develop/source/IIntegrator.h

Can you give us a few hours to update the solution? Then we can reassess its suitability.

**Comment by hsauro** [comment]
I'm about to drive to Hanford so I'll be out of email most of today.

H

**Comment by 0u812** [comment]
Keep an eye on your Geiger counter!

J Kyle Medley, PhD Student
Bioengineering/BPSD, Sauro Lab
University of Washington, Seattle
medleyj@uw.edu

**Comment by hsauro** [comment]
That's right. That's where I'm going....

H

**Comment by hsauro** [comment]
As a matter of interest this is how I would do what you're trying to do in
Delphi:

Create a list that stores registration records. Each registration record
stores an Id (name of integrator) and its class type. In Delphi classes can
be stored in variables, passed in functions etc.

Each integrator registers itself into the list by storing its name and
class type.

The number of integrators is just the size of the list of registered
integrators.  descriptions can be retrieved using a class method.

When a new integrator is requested, the integrator is looked up in the
array using the integrator name which gives access to the class type. From
the class type the integrator object can be instantiated. This avoids the
switch statements in traditional factories which have to be maintained
alongside any new classes that are added. It means that once the factory is
set up it doesn't have to be changed when a new integrator is added to the
code. The only thing that has to be done is that each integrator register
itself.

I'm not suggesting you use this pattern but it might not be possible in C++.

Herbert

**Comment by 0u812** [comment]
That's pretty much what I was thinking except that in C++ we have to pass a function pointer instead of a class id. This is because operator new must be called on a type known at compile time.

Passing a function pointer which constructs the object and returns an integrator base pointer is probably the simplest way.

On July 24, 2015 11:57:42 AM MST, Herbert Sauro <notifications@github.com> wrote:
>As a matter of interest this is how I would do what you're trying to do
>in
>Delphi:
>
>Create a list that stores registration records. Each registration
>record
>stores an Id (name of integrator) and its class type. In Delphi classes
>can
>be stored in variables, passed in functions etc.
>
>Each integrator registers itself into the list by storing its name and
>class type.
>
>The number of integrators is just the size of the list of registered
>integrators.  descriptions can be retrieved using a class method.
>
>When a new integrator is requested, the integrator is looked up in the
>array using the integrator name which gives access to the class type.
>From
>the class type the integrator object can be instantiated. This avoids
>the
>switch statements in traditional factories which have to be maintained
>alongside any new classes that are added. It means that once the
>factory is
>set up it doesn't have to be changed when a new integrator is added to
>the
>code. The only thing that has to be done is that each integrator
>register
>itself.
>
>I'm not suggesting you use this pattern but it might not be possible in
>C++.
>
>Herbert
>
>
>
>On Fri, Jul 24, 2015 at 11:37 AM, Herbert Sauro <uw.hsauro@gmail.com>
>wrote:
>
>> That's right. That's where I'm going....
>>
>> H
>>
>> On Fri, Jul 24, 2015 at 11:22 AM, Kyle Medley
><notifications@github.com>
>> wrote:
>>
>>> Keep an eye on your Geiger counter!
>>>
>>> J Kyle Medley, PhD Student
>>> Bioengineering/BPSD, Sauro Lab
>>> University of Washington, Seattle
>>> medleyj@uw.edu
>>>
>>> On 07/24/2015 10:59 AM, Herbert Sauro wrote:
>>> > I'm about to drive to Hanford so I'll be out of email most of
>today.
>>> >
>>> > H
>>> >
>>> > On Friday, July 24, 2015, wcopeland <notifications@github.com>
>wrote:
>>> >
>>> > > *getIntegratorName()* and *getIntegratorDescription()* are
>methods
>>> that
>>> > > are enforced by the generic Integrator interface, so getting the
>>> > > description should not be a problem.
>>> > >
>>> > >
>>>
>https://github.com/sys-bio/roadrunner/blob/develop/source/IIntegrator.h
>>> > >
>>> > > Can you give us a few hours to update the solution? Then we can
>>> reassess
>>> > > its suitability.
>>> > >
>>> > > —
>>> > > Reply to this email directly or view it on GitHub
>>> > >
>>> > <
>>>
>https://github.com/sys-bio/roadrunner/issues/154#issuecomment-124584234>.
>>> > >
>>> >
>>> > —
>>> > Reply to this email directly or view it on GitHub
>>> > <
>>>
>https://github.com/sys-bio/roadrunner/issues/154#issuecomment-124600002>.
>>> >
>>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>>
><https://github.com/sys-bio/roadrunner/issues/154#issuecomment-124608896>
>>> .
>>>
>>
>>
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/sys-bio/roadrunner/issues/154#issuecomment-124630272

-- 
Sent from my TARDIS with K-9 Mail. Wibbly-wobbly wordy gurdy.

**Comment by hsauro** [comment]
Ok sounds good.

H

**Comment by 0u812** [comment]
Please use [getNumRegisteredIntegrators](http://sys-bio.github.io/roadrunner/c_api_docs/html/rrc__api_8h.html#a53617fbabff8088e10c8bc5deee40353). Should return 4.
```
Number of registered integrators:	 4
  0:
   Name: cvode
   Hint: CVODE hint.
   Desc: CVODE description.
  1:
   Name: gillespie
   Hint: Gillespie hint.
   Desc: Gillespie description.
  2:
   Name: rk4
   Hint: RK4 hint.
   Desc: RK4 description.
  3:
   Name: euler
   Hint: Euler hint
   Desc: Euler description
```
Hints and descriptions up next.
