### ISSUE TITLE
Return <type 'NamedArray'> for r.steadyState()

### ISSUE THREAD

**Issue by matthiaskoenig** [sys-bio/roadrunner#306]
Having a NamedArray as a result of steadyState would make many things much much easier (I can than handle the steadyStates in the same way like simulate results).

See also issue #258

**Comment by 0u812** [comment]
This will be reverted per @hsauro (#333). You will have to call `RoadRunner.steadyStateNamedArray` to get the named array.

**Comment by 0u812** [comment]
On second thought, I think this will break the test suite. I'm renaming to steadyStateSS for the sum-of-squares version. You can continue to use RoadRunner.steadyState for the named array.

**Comment by hsauro** [comment]
We need a dedicated steadystate method for this. We shouldn't change the
current semantics for steadyState(). Have you checked getSteadyStateValues()

Herbert

**Comment by 0u812** [comment]
The trouble is that it breaks everything in the test suite if I revert it. Can your user use `r.steadyStateTime` for now? `r.steadyStateTime` actually returns the sum of squares. (I know it shouldn't be called that but it does do what you want).

**Comment by hsauro** [comment]
We can live with steadystateTime for now (DO NOT document it) but it must
be removed by end of summer. This will give enough time to update the test
suite.

This is what should be done by end of summer:

r.steadyState() should remain as it was orginally, ie it attempts to compute
the steady state and returns the sum of squares to indicate how well it did.

There already exists a:

r.getSteadyStateValues()

that returns an array of steady state values.

We can have an additional method that returns a labeled array, eg

r.getSteadyStateNamesValues()

or something similar.

r.steadyStateTime() *should be deleted*, its not in the documentation and
its name doesn't reflect what it does.

r.steadyStateSS() if present should be deleted since it will be redundant.

Update all documentation.

Herbert
