### ISSUE TITLE
roadrunner not building on linux with updated libsbml dependencies

### ISSUE THREAD

**Issue by matthiaskoenig** [sys-bio/roadrunner#313]
Hi Kyle et al,

I tried to build the latest roadrunner on linux.
Somehow the libsbml dependencies are not found when building on linux (after the latest update 1.4.2 & 1.4.4). Was never any issue before

I attached the build log and script I use for building (so you see the make command).
[roadrunner.zip](https://github.com/sys-bio/roadrunner/files/186884/roadrunner.zip)

The dependencies build without problems, but cannot be resolved when building roadrunner (see line 7883 in log, before none of the libsbml symbols can be found).

Matthias

**Comment by 0u812** [comment]
Hi Matthias,

I think the error is because you have a copy of libsbml in /usr/local which CMake is linking to instead of the one in the roadrunner installation directory. To fix this you can explicitly set the following variables:

```
LIBSBML_INCLUDE_DIR
LIBSBML_LIBRARY
LIBSBML_STATIC_LIBRARY
```


[roadrunner.sh.fix_libsbml_vars.zip](https://github.com/sys-bio/roadrunner/files/186991/roadrunner.sh.fix_libsbml_vars.zip)

I have attached an updated script which I believe will allow you to build roadrunner. Please let me know if you still have trouble. I will try to override the search order for library paths in CMake to prevent this from happening in the future.

**Comment by matthiaskoenig** [comment]
Fixed. Thanks.
