### ISSUE TITLE
Is Gillespie working correctly?

### ISSUE THREAD

**Issue by hsauro** [sys-bio/roadrunner#318]
The following Gillespie simulation produces incorrect results

import tellurium as te
import random

r = te.loada("""
   J0: TetR->; kTbye * TetR
    
   TetR = 1;  // Note one molecule
   kTbye = 0.1; 
end
""")

r.getIntegratorByName('gillespie').seed = random.randint(1, 100)
m = r.gillespie (0, 10)
r.plot()
print m

Changing the seed makes no difference the simulation results. Also The single molecules of TetR disappears immediately. Also kTbye appears to have no effect on the dynamics. 

Typical results from Jarnac for the same model (Time and TetR):

R1{{       0        1} 
R2 {   22.64        0}}

R1{{       0        1} 
R2 {   13.88        0}}

R1{{       0        1} 
R2 {   12.47        0}}

Copasi gives similar results to Jarnac.

**Comment by 0u812** [comment]
First of all, let's all use the same API. Matthias has extensive documentation of how to use the standard roadrunner API for stochastic simulations here: http://tellurium.readthedocs.org/en/latest/tellurium_methods.html#stochastic-simulation. I think we should all use his conventions because they are documented and tested. In particular, this means using r.simulate instead of r.gillespie. So, here's the re-worked example:
```
import tellurium as te
import random
from roadrunner import Logger
Logger.setLevel(Logger.LOG_DEBUG)

r = te.loada("""
J0: TetR->; kTbye * TetR

TetR = 1; // Note one molecule
kTbye = 0.1;
""")

r.setIntegrator('gillespie')
r.getIntegrator().setValue('variable_step_size', True)
m = r.simulate(0,100,steps=10)
r.plot()

print(m)
```

This actually produces the correct output. I've made a few important changes:
* I set the variable_step_size option on Gillespie. Without this option, it just runs a gillespie simulation for `n` steps. The time values don't mean anything. I can see how this might confuse people, but this was the behavior when I inherited the project. There might be a fix warranted here but I will **not** enable variable step by default. That would be inconsistent. Instead, we could do some interpolation or something for fixed step.
* I'm simulating from 0 to 100 with 10 steps. You will notice the output always contains a value at 100. This is for consistency with the other modes of integration. The feature of including the last timepoint was requested by Matthias. Again, this might be confusing in stochastic simulations but nevertheless it is consistent across integrators, and I like consistency.

Now, as for the seed, it is set randomly at startup, so it will be different each time. If you want to use the same seed, you can simply set the seed parameter as you did above:
```
import tellurium as te
import random
from roadrunner import Logger
Logger.setLevel(Logger.LOG_DEBUG)

r = te.loada("""
J0: TetR->; kTbye * TetR

TetR = 1; // Note one molecule
kTbye = 0.1;
""")

myseed = random.randint(1, 100)
r.setIntegrator('gillespie')
r.getIntegrator().setValue('variable_step_size', True)
r.getIntegrator().setValue('seed', myseed)
m = r.simulate(0,100,steps=10)
r.plot()

print(m)
```

You can use one of the short-hands for setting the seed if you like.

**Comment by 0u812** [comment]
I just discovered that the setSeed function Matthias is using in his example doesn't work for me (with the latest tellurium master). That's a tellurium bug.

**Comment by 0u812** [comment]
Btw chances are you probably don't have the setSeed function at all in your dist so you should just use the working example I posted above.

**Comment by 0u812** [comment]
Please disregard my initial reply, I realized it wasn't very organized. Basically what I'm trying to say is that this is the expected behavior, and changing it has various tradeoffs that it would probably be more helpful to discuss in person.

**Comment by hsauro** [comment]
Are you saying that what William saw was expected behavior (the WRONG
behavior) when EVERY other simulator does it differently but actually gets
it RIGHT? I couldn't care less about consistently if the answer is actually
wrong!

**Comment by matthiaskoenig** [comment]
Hi all,
here many issues come together

[1] @Kyle/Kiri all the tellurium issues with the seed and gillespie are fixed for long (weeks) in the master. These have to be in a new tellurium release (It must be easy to create a new release (this should be automatized) so we can release the bug fixes in a timely manner. I am still waiting for the tesedml changes to be in a release.

[2] I can reproduce the problem and roadrunner gives different results than Copasi (it looks like roadrunners jumps from 1 to 0 item with the first step no matter what), whereas other tools give much longer half-times to zero (4-10 seconds). Something is wrong with the roadrunner gillespie!
@Kyle The thing which is wrong that the default behavior of gillespie changed with some recent changes! 
Suddenly one has to set
```
r.getIntegrator().setValue('variable_step_size', True)
```
to get correct results. Which was never the case before. This has to be set by default in gillespie integrator !!! This will fix the issue.

[3] In my opinion one should define the substance units as item and define the reactions as irreversible! Than Copasi can simulate the model directly and ambiguity is avoided
In addition it is important to select the amounts in the timeCourseSelections!

```
%matplotlib inline
from __future__ import print_function, division
import tellurium as te
import random

# Define the reaction irreversible (so COPASI & other tools can handle stochastic simulation)
# Define the substance unit! So it is clear what the substance should be (otherwise other tools will use mole)
r = te.loada("""
model test()
    unit substance = 1 item;
    
    J0: TetR=>; kTbye * TetR 
    TetR = 1; // Note one molecule
    kTbye = 0.1;
end
""")
# Select the amounts
r.timeCourseSelections = ['time'] + r.getFloatingSpeciesIds()
print(r.timeCourseSelections)

# !!! This fixes it, but must be default !!!
r.getIntegratorByName("gillespie").setValue('variable_step_size', True)
for k in range(10):
    r.reset()
    # r.getIntegratorByName('gillespie').seed = random.randint(1, 100)
    m = r.gillespie(0, 10, 101)
    r.plot(m, show=False, loc=None)
# print(m)
print(r.getAntimony(current=False))
print(r.getSBML())
```

**Comment by 0u812** [comment]
Just talked to Herbert and we are going to make `variable_step_size` default for gillespie. For completeness (and consistency with the ODE results), we are also going to include the last time point in the results, even if there is no reaction which occurs at that exact time. However, instead of linear interpolation, we are going to use flat interpolation when gillespie is the selected integrator.

**Comment by 0u812** [comment]
The commit I just made should fix it. Kiri, can you please add a test for this when you get the chance? The things that should be tested are:
* Using different seeds via `r.getIntegrator().setValue('seed', 123)` should produce different results. It suffices to check that the time value of the second row in the results array is different. Example made up data:
```
   time,     [TetR]                    time,   [TetR]
 [[     0,       1]                [[     0,       1]
->[1.2589,       0]                 [7.6215,       0]   *** Different time values
  [    10,       0]]                [    10,       0]]
```

* There should be a row for the end time specified in the call to simulate. You can use model in this example and just check that the value of `TetR` at time t=10 is identical to the value of `TetR` in the second-to-last row. Please let me know if you have any questions.

```
import tellurium as te
import random
from roadrunner import Logger
Logger.setLevel(Logger.LOG_DEBUG)

r = te.loada("""
J0: TetR->; kTbye * TetR

TetR = 1; // Note one molecule
kTbye = 0.1;
""")

r.setIntegrator('gillespie')
r.getIntegrator().setValue('variable_step_size', True)
m = r.simulate(0,10,steps=10)
r.plot()
```

**Comment by 0u812** [comment]
Oops forgot to mention @kirichoi. Please implement the test I posted above when you have time.

**Comment by kirichoi** [comment]
Working on it.

**Comment by kirichoi** [comment]
Added test through 306fb7ab546ed04664b85837d9e209c3b890bdbd.

**Comment by Peter-J** [comment]
The error matthiaskoenig observes in [2] is easily explained with my observation of not producing RCLL-Paths: His simulation returns the time point x but the values after the first reaction after time x even if x is verry verry small and the next reaction takes place at around 4-10 seconds.

Ofcourse roadrunner jumps fom 1 to 0 in the first step, there is only one reaction and GillespieIntegrator.cpp assignes the values AFTER the first reaction AFTER time point x to your time point x so ... what are the values AFTER the first reaction AFTER time point x? Correct: It returns the values after the first and only reaction there is so its the jump from 1 to 0.

See #336 for further details and an easy sollution.
