### ISSUE TITLE
Does getEigenValuesIds return the correct ids? 

### ISSUE THREAD

**Issue by hsauro** [sys-bio/roadrunner#322]
Consider the model below. The output from the model is:

('eigen(x)',)
-0.15

A call to r.getValue ('eigen(x')) will fail but one to getValue ('eigenReal (x)') succeeds. 

What should a call to r.getEigenValueIds() return?

Should it return:

'eigenReal (x)', eigenImag (x) 

or should getValue understand 'eigen(x)' and return a complex number?

import tellurium as te
import roadrunner

r = te.loada("""
   $Xo -> x; k1*Xo;
    x -> ; k2*x;

Xo = 1; k1 = 0.5;
k2 = 0.15;

""")

r.steadyState()
print r.getEigenValueIds()
print r.getValue ('eigenReal (x)')

**Comment by hsauro** [comment]
Kyle will fix this. 15 Feb 2017

**Comment by 0u812** [comment]
Add eigen function for returning complex numbers

**Comment by kirichoi** [comment]
To fix this bug, following changes have been introduced:
* SelectionType EIGENVALUE is renamed to EIGENVALUE_REAL.
* SelectionType COMPLEX is renamed to EIGENVALUE_IMAG.
* SelectionType EIGENVALUE_COMPLEX returns real and imag part of eigenvalue.
* All three SelectionTypes are accessible, but in C++, EIGENVALUE_COMPLEX returns nothing because the return type is double and there's no easy way to return complex number as far as I know without some major changes.
* In Python, custom Python code captures `eigen` selection and returns a complex number.
* `getEigenValueIds()` now returns all possible SelectionTypes related to eigenvalues, including `eigen`, `eigenReal`, and `eigenImag`. Test has been updated to accommodate this change.
