### ISSUE TITLE
Bug when getting rates of change

### ISSUE THREAD

**Issue by hsauro** [sys-bio/roadrunner#325]
The following model results in the error message:

RuntimeError: index out of range in?getFloatingSpeciesAmountRates@LLVMExecutableModel@rrllvm@@UAEHHPBHPAN@Z

import tellurium as te
import roadrunner

r = te.loada("""
    J1:S1 -> S2;  k1*S1;

```
   S1 = 1; k1 = 0.1;
```

""")

r.conservedMoietyAnalysis = True
m = r.simulate (0, 10, 100, ['time', "S2'"])
# This line is ok

m = r.simulate (0, 10, 100, ['time', "S1'"])

Probably cause rate of change is not taking into account the conservation moiety flag so that it only sees S1' and not S2', when it tried to access the indexth position of S2' it fails/

**Comment by 0u812** [comment]
This is a huge enhancement. The library doesn't have the code to do this at all. The only reason you can access the values of conserved moieties is because they are stored as global parameters. It doesn't compute the rates at all, and has no machinery for computing them as far as I can tell.

Fixing this on the Python end using some matrix algebra might take slightly less work, but it would still be a huge task. I'll see what I can do if I manage to find some time. I'm pretty overloaded at the moment.

**Comment by hsauro** [comment]
Postpone fix for the moment then, I've got a workaround I can use.

Herbert

**Comment by hsauro** [comment]
This will require some extra thought, for now add an exception handler around getFloatingSpeciesAmountRates and warn the user that S' (rate of change symbol) for dependent variables when there are conserved moieties is not supported. Workaround is for a user to ask for the independent variables (si) and compute the dependent (sd) rates of change from dsd/dt = L dsi/dt (see equation 7 of metabolic control analysis in a nutshell).

**Comment by luciansmith** [comment]
Exception added:  you now get the message:

"No rate available for floating species S2: if conserved moieties are enabled, this species may be defined by an implied assignment rule instead, and its rate cannot be determined."

Will that work?

**Comment by luciansmith** [comment]
Fixed with https://github.com/sys-bio/roadrunner/pull/837 for now.
