### ISSUE TITLE
Add test case for the following model

### ISSUE THREAD

**Issue by hsauro** [sys-bio/roadrunner#326]
Add a test case to test the following model. It currently crashes due to a bug in roadrunner. Issue submitted and allocated to Kyle.

import tellurium as te
import roadrunner

r = te.loada("""
    J1:S1 -> S2;  k1*S1;

```
   S1 = 1; k1 = 0.1;
```

""")

r.conservedMoietyAnalysis = True
m = r.simulate (0, 10, 100, ['time', "S2'"])

**Comment by kirichoi** [comment]
Wait until #325 is resolved

**Comment by luciansmith** [comment]
Given that S2 has no rate associated with it, since conserved moieties are on, I think this isn't a bug so much as it is a bad error message.  This is now what you get when you run that program:

RuntimeError: No rate available for floating species S2: if conserved moieties are enabled, this species may be defined by an implied assignment rule instead, and its rate cannot be determined.

**Comment by luciansmith** [comment]
Closed with https://github.com/sys-bio/roadrunner/pull/837 for now.
