### ISSUE TITLE
r._CSUM0 not recongnized in conserved cycle models

### ISSUE THREAD

**Issue by hsauro** [sys-bio/roadrunner#378]
Relates to version 1.4.19

Given the following model:

```python
import tellurium as te
import roadrunner

r = te.loada("""
      S1 ->S2; v;
      S2 -> S1; v;
      
      v = 0; S1 = 3; S2 = 4;
""")
r.conservedMoietyAnalysis = True

print r.getConservedMoietyValues() 
print r.model.getConservedMoietyIds()
print r._CSUM0
```

[ 7.]
['_CSUM0']

ERROR:

  File "C:\Tellurium-Winpython\python-2.7.10\lib\site-packages\roadrunner\roadrunner.py", line 73, in _swig_getattr_nondynamic
    return object.__getattr__(self, name)

AttributeError: type object 'object' has no attribute '__getattr__'

r._CSUM0 is not recognized as a parameter in the model, it should be.

**Comment by 0u812** [comment]
Currently, you should be able to access the conserved quantities with `r['_CSUM0']`. I don't think the original long names for the conserved quantities were exported as attributes of the RoadRunner object, so the new ones are not either, but I will add that feature. Please do let me know if the `r['_CSUM0']` syntax does not work though, because that would definitely be a problem.

**Comment by hsauro** [comment]
_CSUM0 should be accessible like any other parameter. So add the feature to
acess _CSUM0 directly.

Herbert
