### ISSUE TITLE
Support SBML L3V2

### ISSUE THREAD

**Issue by 0u812** [sys-bio/roadrunner#379]
Need to implement:
* `rateOf` (only applies to floating species or anything with a rate rule, evaluates to zero otherwise)
* `min`/`max` - return the min or max value of the arguments
* Don't crash for assignment rules with no math (in the test suite)
* Need to bundle libSBML 5.15.0 in deps.

**Comment by kirichoi** [comment]
Initial testing returns with at least 298 tests passing (~53%) for SBML test suite 3.3.0. The result below is for future reference when we tackle each issue.

3.2.0 test result for reference:
- [x] Case 01197: Pass
- [ ] Case 01198: Fails due to VolumeConcentrationRates test
- [x] Cases 01199-01204: Pass
- [ ] Cases 01205-01208: Fails on 1208  - VolumeConcentrationRates test
- [x] Cases 01209-01216: Pass
- [x] Cases 01217-01218: Pass

3.3.0 test result for reference:

- [x] Cases 01219-01223: Pass
- [x] Cases 01224-01233 and 01300-01306: Pass
- [ ] Cases 01234-01247, 01271, and 01300-01306: Fails on 1234-1239, 1241-1243 - `elements without child elements`
- [ ] Cases 01248-01270 and 01293-1299: Fail - `rateOf`
- [x] Cases 01272-01281: Pass - `max, min, rem, quotient, and implies`
- [ ] Cases 01282-01292: Fail - `Boolean values in numeric contexts`
- [x] Cases 01307-01309: Pass
- [x] Case 01310: Pass
- [x] Cases 01311-01315: Pass
- [ ] Cases 01316-01322: Fails on 1318-1322 - `csymbols with names that shadow other parameters or functions` (assignmentRule specific issue)
- [x] Cases 01323: Pass
- [ ] Cases 01324-01338: Fails on 1333
- [x] Cases 01339-01340: Pass
- [x] Cases 01341-01342: Pass
- [x] Case 01343: Pass
- [x] Cases 01344-01394: Fails on 1350, 1359, 1368, 1377, 1386 - `hierarchical models` **(IGNORE - AlgebraicRule)**
- [x] Case 01395: Pass
- [x] Cases 01396-01399: Fail - `combinations of fast reactions` **(IGNORE - FastReaction)**
- [x] Cases 01400-01419: Fail - `rateOf and delay csymbols` **(IGNORE - CSymbolDelay)**
- [ ] Cases 01420-01453: Fails on 1444-1453 - `single reactions that have multiple speciesReferences`
- [x] Case 01454: Fails - `delay csymbol and the VolumeConcentrationRates` **(IGNORE -  CSymbolDelay)**
- [ ] Cases 01455-01460: Fail - `rateOf csymbol with compartments having volumes other than 1`
- [ ] Case 01461: Fail - `rateOf csymbol that points to a parameter`
- [ ] Cases 01462-01463: Fail - `rateOf csymbol with VolumeConcentrationRates`
- [ ] Cases 01464-01465: Fail - `assigned stoichiometries with no MathML`
- [x] Case 01466: Pass
- [x] Cases 01467-01470: Pass
- [x] Cases 01471-01477 and 1778: Pass
- [ ] Case 01478: Fail - `volume concentration rates with a function definition`
- [ ] Case 01479: Fail - `csymbol avogadro`
- [x] Cases 01480-01481: Fail - `stoichiometry math with the delay csymbol` **(IGNORE - CSymbolDelay)**
- [x] Cases 01482-01484: Fail - `rateOf csymbol in an algebraic rule` **(IGNORE - AlgebraicRule)**
- [ ] Cases 01485-01497: Fail - `combinations of uncommon MathML`
- [ ] Case 01498: Fail - `combination of species references in MathML with volume concentration rates`
- [x] Cases 01499-01503: Fail - `algebraic rules with conversion factors and uncommon MathML` **(IGNORE - AlgebraicRule)**
- [ ] Cases 01504-01512: Fail - `volume concentration rates in concert with events of various types`
- [ ] Cases 01513-01514: Fail - `volume concentration rates in concert with initial assignments`
- [ ] Cases 01515-01517: Fails on 1517 - `uncommon MathML in rate rules and with assigned stoichiometries`
- [x] Cases 01518-01524: Passes on 1519 - `csymbol delay with various types of events` **(IGNORE - CSymbolDelay)**
- [ ] Cases 01525-01529: Fail - `rateOf csymbol with various types of events`
- [x] Cases 01530-01533: Pass
- [x] Cases 01534-01539: Fail - `csymbol delay when assigning to stoichiometries, with boundary species, and with fast reactions` **(IGNORE - CSymbolDelay)**
- [ ] Cases 01540-01543: Fail - `rateOf csymbol with boundary species and with assigned stoichiometries`
- [ ] Cases 01544-01546: Fail - `conversion factors in reactions that have a fast attribute value of true`
- [ ] Cases 01547-01551: Fail - `reactions that have fast="true" with function definitions having various kinetic laws`
- [ ] Cases 01552-01554: Fail - `assigning to stoichiometries, but with missing MathML`
- [ ] Cases 01555-01557: Fail - `assigning to boundary species, but with missing MathML`
- [ ] Cases 01558-01560: Fail - `referencing a species reference from a fast reaction` **(IGNORE - FastReaction)**
- [x] Cases 01561-01563: Pass
- [x] Cases 01564-01565: Pass - `uncommon MathML used to assign to kinetic laws of normal and fast reactions` **(IGNORE case 01565 - FastReaction)**
- [x] Case 01566: Pass
- [x] Cases 01567-01570: Fail - `fast reactions with algebraic rules, assignment rules, rate rules, and initial assignments` **(IGNORE - FastReaction)**
- [x] Cases 01571-01572: Fail - `fast reactions with assigned stoichiometries` **(IGNORE - FastReaction)**
- [ ] Cases 01573-01574: Fails on 1574 - `assigned stoichiometries for boundary species`
- [x] Cases 01575-01579: Fail - `algebraic rules with various types of events and event elements` **(IGNORE - AlgebraicRule)**
- [x] Cases 01580-01587: Pass
- [x] Cases 01588-01593: Fails on 1589, 1592, 1593 - `random events with initial assignments, algebraic rules, rate rules, delayed events, and the csymbol delay` **(IGNORE - AlgebraicRule/CSymbolDelay)**
- [x] Cases 01594-01599: Pass
- [ ] Cases 01600-01603: Fail - `missing MathML in delayed events`
- [x] Case 01604: Pass
- [ ] Case 01605: Fail - `random events with additional event assignments with no MathML`
- [ ] Cases 01606-01616: Not Tested (FBC)
- [ ] Cases 01617-01623: Not Tested (FBC)
- [ ] Cases 01624-01625: Not Tested (FBC)
- [ ] Cases 01626-01627: Fails - `random events with stoichiometries and volume-concentration rates`
- [ ] Cases 01628-01630: Not Tested (FBC)
- [x] Cases 01631-01634: Pass
- [x] Cases 01635-01636: Pass
- [x] Case 01637: Pass
- [x] Cases 01638-01640: Pass
- [x] Case 01641: Pass
- [x] Cases 01642-01653: Pass
- [x] Case 01654: Pass
- [x] Case 01655: Pass
- [x] Cases 01656 and 1764-1774: Pass
- [ ] Case 01657: Fail - `species reference with an empty assignment rule`
- [x] Cases 01658-01665: Pass
- [x] Cases 01666-01668: Pass
- [x] Cases 01669-01692: Pass
- [ ] Cases 01693-01702: Fails on 1696, 1697, 1698, 1699 - `function definitions and various events, including ones that fire at t0, and those affected by assignment-time or trigger-time settings`
- [x] Cases 01703-01709: Pass
- [x] Cases 01710-01716: Pass
- [x] Cases 01717-01721: Pass
- [x] Cases 01722-01723: Pass
- [x] Cases 01724-01738: Pass
- [x] Cases 01739-01741: Pass
- [x] Cases 01742-01745: Pass
- [x] Cases 01746-01749: Pass
- [x] Cases 01750-01753: Pass
- [ ] Cases 01754-01757: Fails on 1757 - `initial assignments with various types of events, especially those that fire at time = 0`
- [x] Cases 01758-01759: Pass
- [x] Cases 01760-01763: Pass
- [x] Cases 01775-01777: Pass
- [x] Cases 01778: Pass

**Comment by luciansmith** [comment]
Thanks for getting all this set up!  The tests that are l3v2-specific have the tags:

CSymbolRateOf
BoolNumericSwap
L3v2MathML
NoMathML

If you manage to pass those as you would expect (i.e. pass the ones for which you also support all the *other* tags in that test), let me know.  And if any of them are confusing, let me know about that, too--part of the spec approval process is making sure implementors both understand and can implement the new spec, so if you find anything weird, we still have a chance to fix it.

Also, a handful of the tests have been updated based on feedback from Chris Myers's group, so make sure you grab the latest version.

**Comment by kirichoi** [comment]
libRoadRunner has been updated with partial support for new SBML L3V2 features including min, max, rem, and quotient.

**Comment by hsauro** [comment]
Can you make a list of what's missing for the student who will work on
roadrunner in the summer?

H

**Comment by kirichoi** [comment]
I think the list above is good enough to start. Feature-wise, there's not much to add (we need `implies` and `rateOf`). Most of the failing tests are probably due to some bugs or edge cases, which need detailed inspection of the code and the test files.

**Comment by luciansmith** [comment]
Looks like the top things would be:

* 'implies'
* 'rateOf'
* Missing MathML and/or missing child elements (i.e. an Event with no Trigger).
* Booleans used as numbers and visa versa.

Other things may be one-offs that are odd combinations of different features.

**Comment by kirichoi** [comment]
I am also constantly updating the list here. I marked down certain tests because it tests either algebraicRule, Csymbol delay, or fast reactions.

**Comment by hsauro** [comment]
I think that will be a good starting point for the student to begin to
understand the backend.

**Comment by kirichoi** [comment]
Support for AST_LOGICAL_IMPLIES added via commit 3bb092f6e3e9c099c6ea8efb72cd043fa34998ee.

**Comment by luciansmith** [comment]
With https://github.com/sys-bio/roadrunner/pull/866 we now run every last one of the SBML Test Suite tests.  We check that we pass every test that doesn't have a tag we don't support, and we test that we load the model (and perhaps complain) for every test that *does* have a tag that we don't support, to check that nothing crashes.

The remaining list of tags we don't support are:

   badtags.push_back("AlgebraicRule");
    badtags.push_back("CSymbolDelay");
    badtags.push_back("fbc");
    badtags.push_back("FastReaction");
    badtags.push_back("VolumeConcentrationRate");
    badtags.push_back("RateOf");
    badtags.push_back("AssignedVariableStoichiometry");

We should, eventually, support those last three, and I actually have initial code to support RateOf.  But apart from that, the other tags aren't l3v2-only, so I'm going to close this issue and open others for those specific issues.  Thanks again to Kiri for doing so much on this back in the day.
