### ISSUE TITLE
Method steadyStateNamedArray() is not documented

### ISSUE THREAD

**Issue by hsauro** [sys-bio/roadrunner#382]
The method steadyStateNamedArray() is not documented.

**Comment by 0u812** [comment]
I'm not sure if this is different from `getSteadyStateValues`. At one point, Matthias wanted steadyState to return the steady state values and you wanted it to return the steady state margin. I added this method for Matthias, but I don't think I knew about getSteadyStateValues at the time and maybe he didn't either (or perhaps we didn't realize it performs the steady state calc in addition to returning the values). I think we should leave this undocumented since `getSteadyStateValues` seems to do the same thing, or tell people to use getSteadyStateValues if we have to. We can't remove the method because he is using it.

**Comment by hsauro** [comment]
No they are different, one printout out the names the other doesn't.

rr.getSteadyStateValuesNamedArray()
Out[21]:
        [a],     [b]
 [[ 1.63709, 9.36291]]


rr.getSteadyStateValues()
Out[22]: array([ 1.63709081,  9.36290919])
