### ISSUE TITLE
Gillespie on a grid does not seem to work

### ISSUE THREAD

**Issue by hsauro** [sys-bio/roadrunner#389]
When running the following model I expected 10 points on a grid between 0 and 50, instead I get ten point up to time 0.928226  not 50 as expected.

```
import tellurium as te

r = te.loada ('''
    $Xo -> S1; k1 * Xo;
    S1 -> S2; k2*S1;
    S2 -> $X1; k3*S2;

    Xo = 50; S1 = 0; S2 = 0;
    k1 = 0.2; k2 = 0.4; k3 = 2;
''')

m = r.gillespie (0, 50, 10, ["time", "S1", "S2"])
r.plot()
```

The docs says that will be generate data on a grid, I would have expected time points of 0, 5.555, etc up to 50? 

The delta between each time point is even on a grid:

       time, S1, S2
 [[        0,  0,  0],
  [ 0.309877,  1,  0],
  [ 0.394769,  2,  0],
  [ 0.418176,  3,  0],
  [ 0.470306,  2,  1],
  [ 0.592212,  3,  1],
  [  0.75872,  4,  1],
  [ 0.760471,  5,  1],
  [ 0.815037,  6,  1],
  [ 0.928226,  7,  1]]

PS This code appears to work:

```
import tellurium as te
import numpy

r = te.loada ('''
    $Xo -> S1; k1 * Xo;
    S1 -> S2; k2*S1;
    S2 -> $X1; k3*S2;

    Xo = 50; S1 = 0; S2 = 0;
    k1 = 0.2; k2 = 0.4; k3 = 2;
''')

m = r.gillespie(0, 30)  #<-- no selection list
```

**Comment by kirichoi** [comment]
I thought gillespie algorithm randomizes the step size so won't this be the correct response? By setting the number of points to be equal to 10 it will return the first 10 points it generated.

**Comment by hsauro** [comment]
Docs says that points will be generated on a grid which is actually the
correct thing to do if number of points in specified. If we don't there is
no way to generate a stochastic simulation on a grid, and in any case what
is the point in setting an end time of 50 and it doesn't simulate to that
time?

Kyle do you have any working examples (test example you use to regression
test gillespie) that show the grid functionality working?

**Comment by kirichoi** [comment]
I think we had this discussion before and that's when the current behavior is implemented. 
I believe for gilliespie algorithm, running simulation on a grid is impossible unless you do something like interpolation. If the end time of 50 is desired, simulation should be run without specifying number of time points. If one needs to reproduce the same output, a seed is required. Probably that is how we run the test.

**Comment by luciansmith** [comment]
Even if there are odd time steps going on under the hood, I would expect in this system to *output* ten evenly-spaced time steps between 0 and 50.  If you didn't specify a number of points, I would expect to get the gillespie-generated odd time steps.

You can get the correct output from randomly-spaced data in this case if you know that this is a stairstep function that changes at each new gillespie-generated output time.  So if you want the values at time point 10.0, you look at your list for the time point that is the closest to 10.0 without going over, and use that (renaming the time point to '10.0' instead of '9.99242' or whatever).

**Comment by hsauro** [comment]
You can do grid will gillespie, see Fig 5.10 in Wilkinson Stochastic
Modelling for Systems Biology. I also decribe the approach in my books. For
computing means and stand devs, I am not sure how else one would do it.

**Comment by kirichoi** [comment]
What we can also do is run the gillespie and sample the time points, now that I think about it. That might be something we need to fix.

**Comment by hsauro** [comment]
What do you mean by sample the time points?

**Comment by kirichoi** [comment]
I think Lucian's second paragraph is exactly what I was trying to say.

**Comment by kirichoi** [comment]
I checked the source and this is definitely a bug. I will be adding a test case for this.

**Comment by hsauro** [comment]
What Lucian is suggesting if the approach described in wilkinsons book.

H

**Comment by 0u812** [comment]
Hi all, you can get the Gillespie result on a grid by setting the integrator property `variable_step_size = False`. We actually changed the default behavior back in #318, but it looks like the docs didn't get updated (I think it's because I didn't know about the `gillespie` method - I always just use simulate). I will update the docs.

```python
import tellurium as te

r = te.loada ('''
    $Xo -> S1; k1 * Xo;
    S1 -> S2; k2*S1;
    S2 -> $X1; k3*S2;

    Xo = 50; S1 = 0; S2 = 0;
    k1 = 0.2; k2 = 0.4; k3 = 2;
''')

r.integrator = 'gillespie'
r.integrator.variable_step_size = False # Put results on a grid
m = r.gillespie (0, 50, 10, ["time", "S1", "S2"])
r.plot()
```

Also, @kirichoi, it looks like the commits you pushed caused the build to break. Could you have a look at the [build output in Travis](https://travis-ci.org/sys-bio/roadrunner/builds) for [426](https://travis-ci.org/sys-bio/roadrunner/builds/265837146) through [428](https://travis-ci.org/sys-bio/roadrunner/builds/265843448) and see if you can fix it? Travis will tell you which tests failed in the log. You can run the tests locally using `import roadrunner; roadrunner.runTests()`. Let me know if you need help.

**Comment by 0u812** [comment]
Rather, I should say caused the build to "fail". Travis uses "failing" when the tests don't pass and "broken" when it doesn't compile at all. It's "failing" right now.

**Comment by kirichoi** [comment]
@0u812: I see. However, I am not sure whether it makes sense to specify the integrator as gillespie when you are running the `gillespie` function. I think that might cause some confusion. Is it possible to change the integrator to gillespie by default when executing `gillespie` function? Also, I think it is also necessary to set `variable_step_size = False` by default when the number of points is given. That also is confusing because you expect to see the behavior Herbert expected when number of points is defined.
As for the test, I will be changing the code so that it passes, but it was intended to fail.

**Comment by hsauro** [comment]
This is not what the docs say, reproduced here:

Simulate from time zero to 40 time units, on a grid with 20 points using
the given selection list

>>> result = r.gillespie (0, 40, 20, [‘time’, ‘S1’])

I like the gillepise method becaise it means I don't have to rememeber the
hoops I have to jump through just to do a simple stochastic simulation.

Herbert

**Comment by hsauro** [comment]
Agreed, our overriding philosophy should be to make things as simple as is
possible for the user. Writing three lines jto do a simple stochastic
simulation should be improved.

The call should be as simple as:

m = r.gillespie (0, 50, 10, ["time", "S1", "S2"])

The above will generate a grid and the following not:

m = r.gillespie (0, 50, ["time", "S1", "S2"])


Herbert

**Comment by hsauro** [comment]
I just realized I gave the wrong figure in Wilkionson's book, its Figure
6.10. (Page 154 in the first edition).

Herbert

**Comment by kirichoi** [comment]
Commit https://github.com/sys-bio/tellurium/commit/84f765975e2e1aa6176fb7ef6bf709a17f9324af should fix this issue. The default behavior is changed so that the output is on grid when number of points/steps are specified. Following code can be used to test this:

```
import tellurium as te
import roadrunner

r = te.loada ('''
    $Xo -> S1; k1 * Xo;
    S1 -> S2; k2*S1;
    S2 -> $X1; k3*S2;

    Xo = 50; S1 = 0; S2 = 0;
    k1 = 0.2; k2 = 0.4; k3 = 2;
''')

# kwargs
g1 = r.gillespie (start=0, end=10, points=11)
r.plot()
print(g1[:5])
r.reset()

# args
g2 = r.gillespie (0, 10, 11)
r.plot()
print(g2[:5])
r.reset()

# kwargs steps
g3 = r.gillespie (0, 10, steps=10)
r.plot()
print(g3[:5])
r.reset()

# no points specified
g4 = r.gillespie (0, 10)
r.plot()
print(g4[:5])
r.reset()
```
@0u812: I noticed that the tellurium has changed quite a bit since 2.0 update. I see that gillespie() function is moved to extended_roadrunner module. I presume functionality/usage is the same as before?
