### ISSUE TITLE
Fix integration of random variables

### ISSUE THREAD

**Issue by 0u812** [sys-bio/roadrunner#421]
Currently, a random variable can be added to a deterministic variable via an assignment rule. However, the integrator can't seem to handle these cases (e.g. output is always a straight line).
![rr-rand-var](https://user-images.githubusercontent.com/7402146/31186951-172ace82-a8e5-11e7-9c22-e58454c577fe.jpg)

**Comment by luciansmith** [comment]
This is literally an impossible situation to cover: you need autocorrelation values or something like that to be able to handle the situation.  The best solution would be to notice and error out, or at least warn the user that they can't do what they're trying to do.

This is true if you have random values in a kinetic law, a rate rule, or an assignment rule.

**Comment by 0u812** [comment]
I don't understand why it's impossible. Can't I just evaluate C (above) at every time step the integrator takes?

**Comment by hsauro** [comment]
I would implement a stochastic ode solver, they're quite simple, usually
Euler like algorithms.

Herbert

**Comment by luciansmith** [comment]
No, because the integrator step isn't part of the model.  Assignment rules apply at *all* times, not just at integrator steps.

**Comment by hsauro** [comment]
eg here's one written in Python, its not very long.

https://github.com/lmount/Simple-SDE-solver

and here is a C++/C library:

https://people.sc.fsu.edu/~jburkardt/c_src/sde/sde.html

Herbert

**Comment by luciansmith** [comment]
To explain a little more in-depth:

In the example you provide, C's value, at every time step is literally all possible numbers between 5 and 5.5.  If you halve your integrator step, it will look twice as noisy.  If you halve it again, it'll look twice again as noisy.  The most accurate picture of the model is to have B a line, and C be a solid bar from B to B+0.5 above that line.

If you slightly modified the model to include an event:

A = 1
C := 5+uniform(0,0.5)
E1: at (C>5.25): A = A + 0.5

At the very first time step, A should equal infinity, because the event will have been triggered an infinite number of times.  This is obviously intractable in a normal simulator--you'd have to add a whole new layer of logic to handle it, when in truth, it's simply the case that the model is bad, and the modeler should have done something else.

If C had some sort of autocorrelation value associated with it, that would become more tractable, as it would no longer be a solid bar of values, but an actual random walk through that bar.  But you can't store that in SBML right now, because nobody is doing modeling like that, and we haven't worked out how best to do it.  So for now, your safest bet is to simply refuse to try to simulate anything with a random draw in an assignment rule, rate rule, kinetic law, or event trigger.  (Unless you want to develop a custom annotation scheme to make them tractable, which would be fine.)

**Comment by 0u812** [comment]
Thanks Lucian, I can understand why events would be a problem, but if I had a model without events it should be possible to integrate it using e.g. the stochastic ODE solvers Herbert linked, correct?

**Comment by 0u812** [comment]
Also, doesn't COPASI do something like this under the hood for its hybrid stochastic/deterministic solver?

**Comment by luciansmith** [comment]
I think that stochastic ODE solvers are very different things from assignment rules.  As I understand it, in a stochastic ODE, you have a probability expressed as a likelihood *per time unit* that an event will happen.  In an assignment rule, there's no process in time being described; it's a statement of fact that X always equals f(Y), independent of time.  Once you take time out of the definition, you're stuck.

In a stochastic simulation, you have a 'Reaction' which describes a process that occurs over time.  That can be deterministic or stochastic, and you interpret the kinetic law slightly differently in those two frameworks.  I *think* I might remember that any hybrid stochastic/deterministic solver treats the reactions as stochastic, and the assignment rules/rate rules as deterministic.  I could be wrong about that, though.

**Comment by 0u812** [comment]
I see. Thanks for shedding some light on this!

**Comment by hsauro** [comment]
I'm not sure how you add external noise (via an assignment rule) to a
stochastic ode systems but it must have been worked out. A stochastic ode
is an ode system with a noise term added, I can't remember the
implementation details, but of my past postdocs implemented a sde solver. ,

As for COPASI, how does one test if the hybrid solver is correct? I'm not
sure if there is any theory to help you there.

Herbert

**Comment by luciansmith** [comment]
Closing this--the original issue of using random draws in assignment rules is not tractable, and the related issue of stochastic noise being added to reactions is a different problem that we're not currently planning to tackle.
