### ISSUE TITLE
Not all species listed in r.keys() call. Antimony docs wrong?

### ISSUE THREAD

**Issue by hsauro** [sys-bio/roadrunner#442]
Given the following model:

MODEL_STR = '''
var B_present # According to Ant doc this is a species, but its not!
S -> A; S * 0.2
A + B -> A; deg_k * A * B_present
A -> ; A * 0.005
deg_k = 0.01
'''
model = te.loada(MODEL_STR)
print model.keys()

['S', 'A', 'B', '[S]', '[A]', '[B]', 'default_compartment', 'deg_k', 'B_present', 'init(deg_k)', 'init(B_present)', '_J0', '_J1', '_J2', 'init([S])', 'init([A])', 'init([B])', 'init(S)', 'init(A)', 'init(B)', "S'", "A'", "B'", 'eigen(S)', 'eigen(A)', 'eigen(B)']

1. Why isn't init([B_present]) listed as a key given var B_present?
2. Why is 'init(deg_k)' listed at all, it's a parameter, deg_k does not have an initial condition, only state variables have initial conditions. 

I think there is a [problem with Antimony, too much flexibility on the declaration syntax causes issues I think. I always thought that var S1 declared a species? Apparently not.

**Comment by luciansmith** [comment]
What bit of the docs made you think that 'var A' meant that A would be a species?  I will fix it.

**Comment by hsauro** [comment]
I think its because 1) I thought I had used that in the past, and second I
misread the docs.

Some questions, is

const k1

the same as writing

k1 = 0.3 (k1 is not a reactant or species)?

or should one use

const formula k1?

and what's the difference between the two in terms of a model?

Herbert

**Comment by hsauro** [comment]
Given the previous discussions the model should therefore be:

var species B_present 
S -> A; S * 0.2
A + B -> A; deg_k * A * B_present
A -> ; A * 0.005
deg_k = 0.01
'''

It seems to be easy to miss out the species tag which makes the model is completely different, as did the original author.

**Comment by kirichoi** [comment]
`init()` syntax applies to things other than species (any identifier specified in SBML) and initial global species is actually a thing.

**Comment by hsauro** [comment]
But it shouldn't, in dynamical systems theory only state variables have
initial conditions.  One never talks about parmaeters having initial
conditions.

Yes they have values at the start of the run which could change during the
simulation but they change due to external factors not because the model is
changing them.

Are we using init (k) to allow us to do resetAll()?

Herbert

**Comment by luciansmith** [comment]
If you write

    k1 = 3

and k1 isn't used as a reactant or product, it will be a constant Parameter in the model with a value of 3.

If k1 is ever assigned to (by a rate rule, assignment rule, or event assignment), it will be declared 'constant=false'.

If you want it to be constant=false even though its value never happens to change, you can declare that with

    var k1

You can declare that it should be 'constant=true' with

    const k1

but this is identical to the default, so it won't change anything.

As far as the model goes:

    var species B_present
    S -> A; S * 0.2
    A + B -> A; deg_k * A * B_present
    A -> ; A * 0.005
    deg_k = 0.01

You don't have an initial value for A, B, or B_present here, which means that roadrunner will give them all default values.  However, the default values that roadrunner gives are different depending on whether the identifier is a species or a parameter, if I recall correctly.  I think the default value for all species values is 1.0, and the default value for all parameters is 0.0.  Maybe that's the difference here?  Otherwise, there's no mathematical difference between a species and a parameter, if neither shows up as a reactant or product.

"[state variables] change due to external factors not because the model is changing them."

To declare a state variable in SBML, you must make it a Parameter flagged 'constant=true'.  But Parameters flagged 'constant=false' can indeed be changed by model rate rules, assignment rules, and/or event assignments.

Antimony determines whether a symbol should be constant=true or not by the simple expedient of seeing whether it ever appears as the target of a rate rule, assignment rule, or event assignment.  If not, it declares it 'constant=true', unless the user has explicitly declared it to be variable with the 'var X' syntax.

But in general, 'constant=true' is only used for validation, or as a hint to the simulator whether or not to display the symbol ID.  (Well, and in some cases where there are algebraic rules, but this doesn't apply to roadrunner.)

**Comment by kirichoi** [comment]
We are not using init(k) to reset things.

**Comment by hsauro** [comment]
In tha case init(k) shouldn't exist.

Herbert

**Comment by kirichoi** [comment]
Okay than I will revert dc4b26e3ba588e3cda0887dddcac07e5b28f7a38 (see https://github.com/sys-bio/roadrunner/issues/438) resolve by removing the entry from `keys()`.

**Comment by yarden** [comment]
For what it's worth, I was also confused from reading the docs about the difference between a variable and a variable that's explicitly declared species. I would not have guessed that they are initialized with different values as @luciansmith suggested (I find that counter-intuitive). A clarification on that in docs would be helpful.
