### ISSUE TITLE
Accept specific timepoints for simulate()

### ISSUE THREAD

**Issue by kirichoi** [sys-bio/roadrunner#446]
It would be nice if one could specify timepoints as an array so that `simulate` returns values at the specified timepoints.

**Comment by matthiaskoenig** [comment]
I don't thing this is necessary.
One can interpolate the solution in 2 lines of python code if this is really needed after running a simulation with nonuniform timesteps. I see this even as a dangerous feature because people could just eliminate by accident/purpose part of the dynamics from the solution (by having a large skip where the dynamics is fluctuating moving fast. Personally I think the two options of uniform and non-uniform time course is sufficient. 
One could add a simple interpolate helper in tellurium if this is needed.

**Comment by kirichoi** [comment]
I am not sure whether I follow you. The idea is to have an iteration of simulate calls between multiple defined timepoints. Since nothing in the integration stage is affected, I don't see how it could be dangerous. This can be already done in Python using for loop which I would like to eliminate. I think passing it to C++ should make it a bit faster.
Interpolation is also a good idea but if you can simulate to the exact timepoint, why interpolate despite of errors?

**Comment by matthiaskoenig** [comment]
So probably I misunderstand how the integration is done internally in roadrunner. But providing an array of timepoints should definitely not be implemented as a repeated one step simulation! You will probably copy a lot of unnecessary data around which will make thinks much slower and initialize the simulation routine on every step.
If this is done in the solver it must be done in 1 simulation! which is than only collecting the results at the specified time points, analoque to how a normal uniformtimecourse simulation is performed. Or are you running multiple one step simulations for a uniform timecourse?
Otherwise with the stop and start it will probably be slower than than simple non-uniform timecourse simulation and interpolation afterwards. 
If this feature can be implemented based on a single simulation run internally with roadrunner this makes sense.

**Comment by luciansmith** [comment]
I am amused by this old issue, since Matthias later requested this very feature ;-)  At any rate, it's now implemented (with the optional 'times' argument to 'simulate'.
