### ISSUE TITLE
Accept list of strings for setValue

### ISSUE THREAD

**Issue by kirichoi** [sys-bio/roadrunner#447]
`setValue` should accept list of strings and list of new values so that one can change a lot of parameters at once.

**Comment by bbartley** [comment]
Is this for Python bindings?
In theory SWIG is supposed to let you define typemaps that convert Python list arguments into vectors (C++) or arrays (C).  I looked for an example in the roadrunner interface, but don't think I ever found one.  In the end I had to hack a different solution in the SBOL bindings.

**Comment by kirichoi** [comment]
@bbartley: Could you explain (or point to the code) how you did this?

**Comment by amberhu-uw** [comment]
@kirichoi I actually just tested a solution that doesn't involve changing the SWIG interface. 

`setValues` can be implemented entirely in Python through `roadrunner.py`

This implementation actually works
```
def setValues(self, keys, values):
    for key, val in zip(keys, values):
        _roadrunner.Solver_setValue(self, key, val)
```

The only problem is how can we get `setValues` to be added back into `roadrunner.py` every time that we rebuild `_roadrunner`?

**Comment by amberhu-uw** [comment]
Kiri showed me how we can put Python code in the SWIG interface file through the `%pythoncode%` block. I was able to get a version of this to work on branch fix-447. 

Only thing is that it's a little bit inconsistent with the rest of the interface.
```python
r = roadrunner.RoadRunner('simple.xml')
r.setIntegrator('cvode')
r.integrator.setValue('stiff', False)
r.setValues(['stiff', 'stiff'], [True, False])
```
These do the same thing, but `setValues` is a member of the RoadRunner object instead of the Solver object, because that's where the SWIG `%pythoncode` block puts everything. I will look into if there is any way to insert the Python code into the Solver class

**Comment by amberhu-uw** [comment]
I realized that the specific `%pythoncode%` block I was putting it into was extending the RoadRunner object. I found the block that extends the Solver class, and have put `setValues` in there.

A small note about adding Python code in the SWIG interface, if you use tabs, it won't compile, and will complain about indentation issues
