### ISSUE TITLE
Indexing Error in CSR Matrix

### ISSUE THREAD

**Issue by amberhu-uw** [sys-bio/roadrunner#472]
I was running libSBML test 01211, which actually passes normally, but when run in debug mode an assertion fails. 

This failure is an index out of bounds error, which is caused by [line 18 in rrSparse.h](https://github.com/sys-bio/roadrunner/blob/cc46626ebdc930149ccbdbe6bd21cc02f6c3744b/source/rrSparse.cpp#L118) which is a memcpy.

There is a note at the top of the definition of `csr_matrix`: 

>This should eventually get replaced when we use a numeric library
which support sparse storage.

I'm not familiar with this data type, but I'm guessing that if it causes errors even when being used correctly we should correct it before it causes stranger errors. 

Git blame shows that the original author was Andy on 7/31/2013. I can take a look at this issue later, but if anyone has any useful information or just experiences with the CSR Matrix it would be greatly appreciated.

EDIT: Looks like it's happening in both 1211 and 1212, not sure about other tests

**Comment by hsauro** [comment]
Adding sparse matrix support would be a major effort. I've not seen the
code, so for now I would log it as an issue and if you have time larger on
return to the issue to see if it can be fixed.

Herbert

**Comment by luciansmith** [comment]
An index out of bounds error in a memcopy is definitely an issue; I'm also unfamiliar with the code at this level of roadrunner, though.

However, I do know the tests, and this particular one has an 'leq' function with three children instead of just two.  If you edit the SBML to remove the first '5', re-run the test, and the assert goes away, the problem is almost certainly due to one part of the code assuming that 'leq' only has two arguments, and a different part of the code actually checking to see how many children of 'leq' there are.  

If the assert fires anyway, then the 'leq' is a red herring, and something else is the problem.  The model is already pretty simple, so I'm not sure how to simplify it further--maybe take out the entire Trigger and replace it with 'False'?

That's about as much as I can diagnose from here.  No idea why this situation would involve sparse matrices...

**Comment by luciansmith** [comment]
Looks like Andrew fixed this a while back--test 1211 now passes.
