### ISSUE TITLE
How to plot high res plot from r.plot?

### ISSUE THREAD

**Issue by hsauro** [sys-bio/roadrunner#484]
How does one plot a high-resolution plot from r.plot()?

I tried

r.plot()
plt.savefig('c:\\tmp\\filename.png')

but that didn't work

**Comment by kirichoi** [comment]
Fixed with commit https://github.com/sys-bio/tellurium/commit/1830c135fdb665dbc2f994f847733565d7a7378b. In matplotlib environment, r.plot will accept two additional arguments, `savefig` and `dpi`. `savefig` accepts full path to the figure. File extension specifies which format you wish to save the figure as. `dpi` can be specified to change the dpi of raster graphics, i.e. png.
