### ISSUE TITLE
getEventIds does not work

### ISSUE THREAD

**Issue by kirichoi** [sys-bio/roadrunner#516]
`getEventIds()` does not work. `SelectionRecord::EVENT` is not functioning properly? However, `getEventId()` with index works.

**Comment by evilnose** [comment]
It looks like `getEventIds` calls `getIds`, in which the code for adding Event IDs were commented out in [this commit](https://github.com/sys-bio/roadrunner/commit/b6b97a5a95871de4e8f2c209fc02a04cfd764db3), which fixes #440 (LS EDIT: not 444) .

Should this be the desired behavior of `getIds()`? Right now I could either un-comment the code that adds the Event IDs and thus revert the previous commit, or I could modify the `getEventIds` function to call`symbols->getEventIds` directly instead of `getIds`.

**Comment by luciansmith** [comment]
I think we should say that 'getIds' returns the IDs of everything in the model with mathematical meaning.  Since events do not, I would say to solve it using your second option: modify the function to call `symbols->getEventIds` directly.

**Comment by luciansmith** [comment]
Looks like this works--the following python script functions as expected:

import tellurium as te

r = te.loada("""
  e = 10
  E0: at(time>3): e=5
""")

print(r.model.getEventIds())
