### ISSUE TITLE
Move away from dynamically-sized LLVMModelData

### ISSUE THREAD

**Issue by amberhu-uw** [sys-bio/roadrunner#523]
The fact that the LLVMModelData's size is unknown at compile-time has been a big pain to debug in the past and the source of much confusion. You can see [here](https://github.com/sys-bio/roadrunner/blob/8066a505389705ff3701860d65937a17377d82a5/source/llvm/LLVMModelData.h#L214) that a lot of the data is just represented a zero-width variable `double data[0]`, meaning that when we are debugging it, there is no way to reasonably inspect the values inside the data. The only way is to hack it by doing pointer arithmetic and evaluating it in the debugger console. 

Note how the size of the values here are defined by *other* values in the LLVMModelData? This is an instance of so-called dependent typing, which is not supported by C++, meaning that the debugger cannot reason about the data inside of it. I suggest that we rewrite it so that `data` is replaced by ten pointers to their respective arrays. I'm not sure why it was originally written like this, possibly to try to squeeze out every last drop of performance, but this is really not maintainable.

This would require some rewriting, but I talked to @hsauro today and we're hoping to make maintainability a priority in the near future. The good thing is that it's a straightforward fix, we just need to put in the hours.

**Comment by amberjhu** [comment]
ModelDataIRBuilder.h needs better documentation. For example, what is a GEP? I need to figure out how the ModelData is being constructed and modified by LLVM to figure out how to optimize it.

EDIT: https://llvm.org/docs/GetElementPtr.html

**Comment by amberjhu** [comment]
I know that spatial locality is important for cache optimization, but I still think we should move to something that can be expressed in the type system because it's very hard to both debug and understand in the first place. 

We can mitigate some of the locality issues by allocating a chunk of memory large enough to hold the LLVMModelData and all the things it will point to, so that we can keep hitting the same line(s) in cache.

**Comment by faye-u** [comment]
@andrewhu-uw Andrew, should I add a new branch for this issue?

**Comment by amberjhu** [comment]
@mengfy0718 Yeah, let's make a branch off of `llvm-6`

**Comment by faye-u** [comment]
@andrewhu-uw Andrew, I am still a little bit confused about what we are trying to do here.

I understand currently that ten data arrays are stored continuously and represented by a zero-sized array in LLVMModelData. When LLVLModelGenerator calls createModelData(), it will first get and store the size of each data array and then allocate new memory for LLVMModelData struct and also ten dynamically-sized data arrays.  

I saw that you suggested to rewrite it so that data is replaced by ten pointers to their respective arrays. But there are already ten alias pointers pointing to each array and we can easily track their values in the watch window of the debugger. I am not sure why this is not maintainable and why this would cause a problem during the debugging. Could you explain a little bit more so that I could redesign a better data structure here? Do you think changing it to a fixed-sized array is good enough to fix the problem?

**Comment by amberjhu** [comment]
@mengfy0718 Oh shoot, you're totally right! I missed the `*Alias` pointers when I read the .h file myself. Could you add something to the class documentation in `LLVMModelData.h` that explains what the alias is, that would be very helpful. It kind of freaked me out when I saw the `data[0]` and thought I would have to calculate the offset by hand when debugging.

**Comment by faye-u** [comment]
@andrewhu-uw Sure! I will add the documentation. So we are good with the dynamic size?

**Comment by amberjhu** [comment]
@mengfy0718 Yes, I think as long as we have those pointers there, so we don't have to do any arithmetic, we're fine. You can close the issue once the documentation has been added.
