### ISSUE TITLE
Check that we have up to date SBML test suite

### ISSUE THREAD

**Issue by amberjhu** [sys-bio/roadrunner#535]
I'm not really sure if the tests that are run by run_test_suite are up to date. 

1. Do we have the most up to date SBML test suite?
2. If not, how can we add the tests to our test suite?

It also looks like we eventually need to update the results of our tests as per #288 but we'll come back to that issue later.

**Comment by kirichoi** [comment]
[Test suite version 3.3.0](http://sbml.org/Software/SBML_Test_Suite) is the latest version which I believe is the one we are [using](https://github.com/sys-bio/roadrunner/commit/34a40bd13f5b1cd9c322053df652be50b95459fd#diff-76a6e1a452d2f7a5539ede1008aa74fa).
You might notice that the commit d97c53c09b2773cce45298a2df564547a35fac92 actually commented out tests from test suite version 3.3.0 for now because we do not fully support SBML L3V2 (https://github.com/sys-bio/roadrunner/issues/379) yet.

**Comment by luciansmith** [comment]
In particular:

https://github.com/sys-bio/roadrunner/issues/379

**Comment by CiaranWelsh** [comment]
This has been handled by Lucian I believe
