### ISSUE TITLE
Implement C++ ExecutableModel

### ISSUE THREAD

**Issue by amberjhu** [sys-bio/roadrunner#553]
This would be a relatively low priority task, but would get more important as we think about the future of roadrunner. As far as I know, we have never implemented a C++ ExecutableModel, we've just always used the LLVMExecutableModel. I have some doubts about the efficiency of the LLVMExecutableModel, so I thought it wouldn't be that hard to write up an implementation of the ExectuableModel interface that just does the computation directly, in a naive way, and then compare that to the performance of LLVMExecutableModel.

If it turns out that LLVMExecutableModel is actually slower when factoring in compile time, that would be worrying, since LLVM often complicates adding new features, #520 in particular comes to mind. I spent a long time pouring over LLVM documentation and I'm still not sure if it's possible to implement this feature without destroying performance. If we had a C++ implementation of ExecutableModel, this would be much easier, and definitely possible.

**Comment by CiaranWelsh** [comment]
I have also thought of doing this, for the same reasons: when running lots of models roadrunner is slow because of the time it takes to JIT compile. As @hu-a suggests, a C++ implementation would speed model creation and would be beneficial in some situations. 

Another note on this is that the code used by roadrunner for JIT compiling is quite old now and the llvm developers have made a lot of improvements. It would take some effort but a llvm-11 implementation of `rr::ExecutableModel` may also be worth considering.

**Comment by luciansmith** [comment]
There's an existing C++ implementation from probably 2015 or something that you can enable with a CMake flag.  I'm virtually certain that it would fail to compile nowadays, and I know that there were a lot of gaps back in the day (i.e. I think events are not supported at all).  But looking at that is where I would start.

**Comment by CiaranWelsh** [comment]
Yes, when building the new build system I tried to get the C version working but it didn't compile. I actually wouldn't mind giving this a pop though.

**Comment by luciansmith** [comment]
So, with the new LLVM13, compile time with LLVM was significantly reduced directly, so I think that lowers the priority of a C++ version that we write ourselves.  As such, I'm closing this issue.
