### ISSUE TITLE
Warnings and Notices stacking in Spyder

### ISSUE THREAD

**Issue by luciansmith** [sys-bio/roadrunner#675]
Herbert got roadrunner into a configuration where it was warning him about things it hadn't warned him about before, and then every time he ran it, the warning list would be *added to* instead of having been cleared when displayed.  If we can reproduce what was going on, this needs to be fixed.

**Comment by kirichoi** [comment]
I have reproduced this issue and it seems like it only happens on Spyder 4.1.4 and onwards. Potentially due to some 'fixes' they made. `roadrunner.Config.setValue(roadrunner.Config.ROADRUNNER_DISABLE_WARNINGS, 3)` can be used as a temporary workaround, but I think we need to check our logging system. Do we want these warnings to be printed? If yes, we should check why the console is printing warnings multiple times. If no, we should suppress the warnings by default from roadrunner side.

**Comment by luciansmith** [comment]
I filed a bug report with spyder for this issue:  https://github.com/spyder-ide/spyder/issues/13991

It should be straightforward to disable warnings by default, though.  But if someone turns them on, we don't want them to stack like this.

**Comment by luciansmith** [comment]
Update:  the 'stacking' behavior is indeed a spyder bug, and they're fixing it!  So yay.

Also, I'm lowering the default reporting level to 'error' for python (instead of 'notice'), since in Spyder, you get all the messages at the end of the run *after* the output, so you have to scroll up to see what you actually want.  However, errors still seem like they'd be useful information.

**Comment by luciansmith** [comment]
Default warning level changed in https://github.com/sys-bio/roadrunner/pull/705/commits/8645fdedac8e4e12af7529cf19065e24715f2773

Once Spyder is fixed, we can close this.

**Comment by luciansmith** [comment]
Finally fixed with Spyder 5.2. https://github.com/spyder-ide/spyder/commit/f2632652bc7ff937fa5aa47176b829cc44be6120

Next time we update Spyder, it should be fixed.
