### ISSUE TITLE
How to recalculate InitialAssignments after model changes?

### ISSUE THREAD

**Issue by matthiaskoenig** [sys-bio/roadrunner#710]
Hi all,

I have the following problem: I have InitialAssignments which calculate values via initial assignments based on other values in the model, e.g. an initialAmount of a species `A1` which is calculated from a parameter `D` via `D*2`. 
I now want to change parameters in the model (here `D`) and reevalutate all InitialAssignments with the new parameters. As I understand the SBML specification the InitialAssignments should be reavaluated by default!, because I have not started a simulation yet. This are basically model changes before a simulation.

The SBML specification states
> an InitialAssignmentdefinition only applies up to and including the beginning of simulation time, i.e., t≤0, while an AssignmentRule applies at all times

So if I change D the initialAssignment should be reavaluated if I have not run any simulation with the model yet.

Apparently roadrunner does not do this. This particular behavior is also not tested in the SBML test suite, because this is something which happens in the context of simulations not with a freshly loaded model. This affects things such as SED-ML model changes, because here the reevaluation of the InitialAssignments must happen if changes affect InitialAssignments. Also it makes it difficult to work with model with InitialAssignments in general.

It would be important to have a simple way to reevaluate all initial assignments in a model.
This issue affects exchange of simulations via SED-ML because tools such as JWS online handle the reavaluation of InitialAssignments differently.

Attached an example showing the problem
[initial_assignment.zip](https://github.com/sys-bio/roadrunner/files/5491186/initial_assignment.zip)

```
from pathlib import Path
import roadrunner
from matplotlib import pyplot as plt
import pandas as pd


def plot_results(s: pd.DataFrame, title=None) -> None:
    fig = plt.figure()
    ax = fig.gca()
    ax.plot(s.time, s.A1, label="A1")
    ax.legend()
    ax.set_title(title)
    ax.set_ylabel("amount")
    ax.set_xlabel("time")
    plt.show()


if __name__ == "__main__":
    model_path = str(Path(__file__).parent / "initial_assignment.xml")

    # default simulations
    r = roadrunner.RoadRunner(model_path)  # type: roadrunner.ExecutableModel
    r.selections = ["time"] + r.model.getGlobalParameterIds() + r.model.getFloatingSpeciesIds() + [f"[{key}]" for key in r.model.getFloatingSpeciesIds()]
    s = r.simulate(0, 10, 100)
    s = pd.DataFrame(s, columns=s.colnames)

    # change of parameter before simulation
    r2 = roadrunner.RoadRunner(str(model_path))  # type: roadrunner.ExecutableModel
    r2.selections = ["time"] + r2.model.getGlobalParameterIds() + r2.model.getFloatingSpeciesIds() + [f"[{key}]" for key in r2.model.getFloatingSpeciesIds()]
    r2["D"] = 10  # ! InitialAssignment must be recalculated according to SBML specification !
                  # FIXME: at least a manual reevaluation of InitialAssignments must be possible now!
    s2 = r.simulate(0, 10, 100)
    s2 = pd.DataFrame(s2, columns=s2.colnames)
    # A1 is 10, but should be 20 (D*2)

    plot_results(s, title="s")
    plot_results(s2, title="s2")
```

As far as I remember there is a way to hack the `SelectionRecord` in combination with `reset` to evaluate the InitialAssignments, but cannot figure out how to get a workaround for now.
I.e. something in the direction of 
```
r.reset(SelectionRecord.DEPENDENT_INITIAL_GLOBAL_PARAMETER)
```
but I would have to now how to get the SelectionRecords for the initial assignments.

This would be required to be able to implement model changes correctly and would also be very helpful, because I often have InitialAssignments I want to reavalute after changing some variables.

How can I reevaluate InitialAssignments with the current model variables/state?
Best Matthias

**Comment by luciansmith** [comment]
Roadrunner assumes that any manipulation of the model is post-time-zero manipulation, and that it therefore does not affect any initial values.

It looks like you might be right about being able to do something with the SelectionRecords, but to me, the method that makes the most sense it to use the "init(var)" keyword.  If you want to change the initial value of something, you *don't* use the r.s1 or r["s1"] syntax:  instead use r["init(s1)"].  Then after you've done that, calling 'resetAll()' will recalculate everything.  Here's an example:

```
import tellurium as te

r = te.loada("""
a = 3
b = a*2
""")

r.selections = ["time", "a", "b"]

r["init(a)"] = 5
r.resetAll()

results = r.simulate(0, 10, 10)
r.plot()
```

This should, I think, allow you to do what you want.

I could see the value in a 'recalculateInitialAssignments()' function.  (Or 'calculateAndApplyInitialAssignments'?  'calculateInitialAssignmentsAndApply()'?)  but I'm not 100% sure it would work as expected, and might be a little too 'inside baseball' to be easily understood by the average user.  If, when called, it recalculated (in dependency order) all initial assignments, but did *not* recalculate any initial values, some odd situation could arise.  Consider the following program:

```
r = te.loada("""
a = 3
b = 2/3
J0: a->b; k0*a
k0 = 0.5
""")

r.simulate()
print("a at steady state =", r.a)
print("b at steady state =", r.b)

r.recalculateInitialAssignments()

print("a after IA reset =", r.a)
print("b after IA reset =", r.b)
```

The output would be:

```
a at steady state = 0.24625661328427903
b at steady state = 3.4204100533823873
a after IA reset = 0.24625661328427903
b after IA reset = 0.66666666666666667
```
This is because you can't store '2/3' in the 'value' attribute of an SBML element, so it was implemented as an initial assignment instead.

The more I think about it, the more I think you probably just want the 'init(var)' keyword.  You could do something like the following:

```
r.simulate()
[...]
r["init(S1)"] = r.S1
r["init(S4)"] = r.S4
r["init(S6)"] = r.S6
r.resetAll()
```

This would be easier code to read, too:  you would clearly be setting the initial value of those three elements to be their current values in the simulation.

It could be that I misunderstood what you want, though, and that there are other solutions out there.  I'm more than happy to add other things if we can figure out a good way to be clear about it.

**Comment by matthiaskoenig** [comment]
Hi Lucian,
thanks for the info. Yes, init allows to set values. 
What I want to do is something else ;) I want to re-evaluate the AST-node math in the InitialAssignments, i.e. the formulas of the objects defined in the ListOfInitialAssignments.

Often you have a lot of logic in the InitialAssignment which ensure correct model behavior and initialisation.
E.g. you want to set the initial value of the sum of two metabolites. 
```
init(S_total) = S + Sp
```
This depends on the initial value of S and Sp. 
If you change the init(S) or init(Sp) it must be possible to reevaluate the corresponding InitialAssignment math. 

There are many constraints in models of this kind. The initial assignments allow to encode these initial logic with the abilty to have a state variable. The only other option is to have an AssignmentRule, but then I loose the ability of dynamically modeling variables, because these are just rules.

What I want is `reevaluteInitialAssignmentMath()` which is reavaluting the InitialAssignments with the current model state. By this I can bring the model in a consistent initial state based on the InitialAssignment logic.

**Comment by matthiaskoenig** [comment]
Sorry, to clarify. As I understand `resetAll` it has side effects which are not what I want. The documentation states it resets all parameters to the values when the model was loaded (this is most likely incorrect and threw me off):

> resetAll
> Resets all variables, species, etc. to the CURRENT initial values. It also resets all parameter back to the values they had when the model was first loaded

This is most likely a documentation issue and should be clarified. I.e. the real thing `resetAll` does (or should do) is

> resetAll
> Resets all variables, species, parameters etc. to the CURRENT initial values. These are either the values they had when the model was first loaded or if set via the `init` syntax the corresponding `init` values.

This would solve my issue.

**Comment by matthiaskoenig** [comment]
See here the problem with the example model:
[initial_assignment.zip](https://github.com/sys-bio/roadrunner/files/5516295/initial_assignment.zip)
```
import roadrunner
import pandas as pd

# Loading model and simulating
model = roadrunner.RoadRunner("initial_assignment.xml")  # type: roadrunner.ExecutableModel
model.selections = ["time", "D", "A1", "[A1]"]

s = model.simulate(0, 100, steps=11)
s = pd.DataFrame(s, columns=s.colnames)
print(s.head())

del model
del s

print('-' * 80)

# Changing initial value of D 
model = roadrunner.RoadRunner("initial_assignment.xml")  # type: roadrunner.ExecutableModel
model.selections = ["time", "D", "A1", "[A1]"]

# Setting initial value of D
# This should allow to update the initial value of A1 which is
#     init(A1) = 2 * D = 4 !!!!!!
model["init(D)"] = 2
# re-evalutating initial assignments, i.e. changing to CURRENT initial state
model.resetAll()

s = model.simulate(0, 100, steps=11)
s = pd.DataFrame(s, columns=s.colnames)
print(s.head())
```
Results in 
```
        time    D    A1  [A1]
0   0.000000  5.0  10.0   5.0
1   9.090909  5.0  10.0   5.0
2  18.181818  5.0  10.0   5.0
3  27.272727  5.0  10.0   5.0
4  36.363636  5.0  10.0   5.0
--------------------------------------------------------------------------------
        time    D    A1  [A1]
0   0.000000  2.0  10.0   5.0
1   9.090909  2.0  10.0   5.0
2  18.181818  2.0  10.0   5.0
3  27.272727  2.0  10.0   5.0
4  36.363636  2.0  10.0   5.0
```
You can see the init change of D is applied, but the InitialAssignment of `init(A1) = 2 * D =4` is not applied in the second simulation! A1 is still 10?
So how can I change D and get the initialAssignment depending on D applied ?

**Comment by matthiaskoenig** [comment]
Sorry for the spam. So most likely the thing I want is something in the direction of
```
model["init(D)"] = 2
model.resetAll()
model.reset(SelectionRecord.DEPENDENT_FLOATING_AMOUNT)
model.reset(SelectionRecord.DEPENDENT_INITIAL_GLOBAL_PARAMETER)

s = model.simulate(0, 100, steps=11)
s = pd.DataFrame(s, columns=s.colnames)
print(s.head())
```
```        time    D   A1  [A1]
0   0.000000  2.0  4.0   2.0
1   9.090909  2.0  4.0   2.0
2  18.181818  2.0  4.0   2.0
3  27.272727  2.0  4.0   2.0
4  36.363636  2.0  4.0   2.0
```

But unfortunately I have no idea if this is correct and works for complex cases (i.e. dependency trees of initial assignments with parameters, volumes, species, ... in the dependency tree). My experience with the SelectionRecords is that they have a ton of side effects I don't understand. 

In my opinion the resetAll() is buggy and should be updated to do the following:
- reset model to initial state when loaded
- apply all defined `init` changes (be it on species, parameters, compartments, ....)
- re-evaluate all InitialAssignmentRules with exceptions of rules on variables set via explicit `init`

This brings the model actually to the CURRENT initial state.

**Comment by matthiaskoenig** [comment]
Last update on this. There is one problematic case which must be handled cleanly. 
It is basically if one wants to set an initial value for something which has an initial assignment rule. In such cases the set `init` value has precedence and a warning should be given that the corresponding InitialAssignment rule is not applied. 

In the example above: 
`init(A1) = 20` 
should give a warning stating: 
```
Initial value set for variable 'A1' with InitialAssignmentRule 'init(A1) = D*2', 
the InitialAssignmentRule will be ignored.
```

**Comment by luciansmith** [comment]
You are correct that while my example worked, other examples like yours do not, for unclear reasons.  I'm working on this (and the related bug you reported) and will report back if I make any progress!

**Comment by matthiaskoenig** [comment]
Hi Lucian,
this is great. This is definitely a major problem with roadrunner and creates a lot of problems in my simulation experiments (SED-ML on top of roadrunner).

Just to comment. This is a duplicate of https://github.com/sys-bio/roadrunner/issues/328 which I opened 4 years ago ;)
I just dropped InitialAssignments from all my models for the last years. But now I have to exchange legacy models and work with models I cannot control (i.e. in hierarchical model composition to existing models with initial assignments). So a solution would be amazing.

**Comment by luciansmith** [comment]
@matthiaskoenig : I am working on a solution to this!  I am pretty close, but want to make sure what I'm implementing will work for you.

The basic idea of how you would do it would be to set new initial values, then reset everything:

```
r.setValue("init(X)", 5)
r.setValue("init(P2)", 3.2)
r.resetAll()
```
Will that work?

Since we can only reset categories of elements, I can't make it so that if you change the *current* value of one parameter, and want to recalculate the initial value of a different parameter, since the current value you changed would itself get reset in the 'reset the parameters' sweep.  But it would be possible to reset the current value of one thing, and then reset a different type of thing:  you could set the current value of a parameter and reset the floating species, for example, and the floating species would use the current values of the parameters.

But if you want to mix and match, setting new initial values will now be correctly propagated to the rest of the model, including initial assignments.

**Comment by matthiaskoenig** [comment]
@luciansmith Perfect. This works for me. 
Thanks for looking at this.

**Comment by luciansmith** [comment]
To completely fix this, both roadrunner and tellurium need to be updated, because tellurium overwrites roadrunner's 'resetAll' function with the old incorrect version.  To do this by hand, delete the 'resetToOrigin' and 'resetAll' functions from tellurium/tellurium/roadrunner/extended_roadrunner.py

However, with that, it's now fixed, with https://github.com/sys-bio/roadrunner/pull/818 and will be in the next release!
