### ISSUE TITLE
Unpin numpy version in python packages

### ISSUE THREAD

**Issue by matthiaskoenig** [sys-bio/roadrunner#726]
In the latestest roadrunner 2.0.4 release the numpy version in the python packages is pinned to `0.19.3`. As a consequence libroadrunner does not work with other libraries requiring other/higher numpy versions.
E.g. I get the conflicts:

```
The conflict is caused by:
    sbmlutils 0.4.5 depends on numpy>=1.19.5
    libroadrunner 2.0.4 depends on numpy==1.19.3
```
Libraries should never be pinned to exact version if not absolutely necessary.
Change `numpy==1.19.3` to `numpy>=1.19.3` for roadrunner.

**Comment by luciansmith** [comment]
I had to pin it to 1.19.3 because 1.19.4 is broken on Windows due to a Windows bug that is in the process of being fixed, but is not fixed yet.

1.19.5 (which was only released a week or so ago) apparently works on Windows, but if I require 1.19.5 (or greater), installation hangs while it tries to figure out all the other compatibility issues.

**Comment by matthiaskoenig** [comment]
Makes sense. Just don't forget to unpin this ;)
I relaxed my dependencies to `numpy>=1.19.3` for now as a workaround.
