### ISSUE TITLE
Remove unimplemented integrator options

### ISSUE THREAD

**Issue by jonrkarr** [sys-bio/roadrunner#808]
Some of the Gillespie integrator options are not implemented. This makes the documentation misleading. These should be removed
- initial_time_step
- maximum_time_step

See https://github.com/sys-bio/roadrunner/blob/e1be6c46234e3f8996cd56bc13f23741b2bc3868/source/GillespieIntegrator.cpp#L198

**Comment by luciansmith** [comment]
Fixed with https://github.com/sys-bio/roadrunner/pull/860:  removed the 'initial_time_step' option, and implemented the maximum_time_step option.

If you could actually use the initial_time_step option, let me know--it didn't seem like a useful parameter for the Gillespie algorithm, but that assumption could be wrong.

**Comment by jonrkarr** [comment]
I think these would be strange options for SSA. They would diverge from other implementations.

**Comment by jonrkarr** [comment]
These seemed like options that were simply copied from continuous integrators and never implemented.

**Comment by luciansmith** [comment]
That makes sense.  I assumed 'maxumim step size' was for when you want output at least every n time units for a variable step size integration.

**Comment by jonrkarr** [comment]
When used with SED-ML, isn't this covered by number of steps of uniform time course.

**Comment by luciansmith** [comment]
This is a variable step size integration, which is on by default for the gillespie integrator.  Basically, you record when a stochastic event happens, regardless of how long it's been since the last event.  So one simulation might go from 0 to 5 and have 15 steps (of varying widths) and the next one might have 60.  

Alternatively, you can give it a number of steps and no end time, in which case you just record the first n stochastic events that happen.

If you (now) set the maximum_time_step, it won't go more than that amount of time without recording any output.  So if you have a simulation from 0 to 50 and set a maximum step size of 20, it'll record at least three steps (20, 40, and 50) even if nothing ever happens.

A SED-ML uniform time course isn't compatible with a variable step size integration.  This is why we proposed that 'numberOfSteps' be made optional, but this was eventually rejected.

**Comment by jonrkarr** [comment]
Non-uniform time course with variables steps could now be done with the new SED `Analysis` class.

**Comment by luciansmith** [comment]
Yup!
