### ISSUE TITLE
No matching distribution found for libroadrunner>=2.1.0 on Python 3.7 MacOS 10.14

### ISSUE THREAD

**Issue by matthiaskoenig** [sys-bio/roadrunner#879]
Some issue of a student (@sankha555) of mine with latest release.

```
(sbmlenv) sankha-das:sbmlutils maniklaldas$ pip install -e . --upgrade
Obtaining file:///Users/maniklaldas/Desktop/sbmlutils
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
    Preparing wheel metadata ... done
Collecting markdown-it-py>=1.1.0
  Using cached markdown_it_py-1.1.0-py3-none-any.whl (83 kB)
Collecting openpyxl>=3.0.7
  Using cached openpyxl-3.0.9-py2.py3-none-any.whl (242 kB)
Collecting fastapi>=0.68.2
  Using cached fastapi-0.70.0-py3-none-any.whl (51 kB)
Collecting uvicorn>=0.14.0
  Using cached uvicorn-0.15.0-py3-none-any.whl (54 kB)
Collecting matplotlib>=3.4
  Using cached matplotlib-3.4.3-cp37-cp37m-macosx_10_9_x86_64.whl (7.2 MB)
Collecting python-multipart>=0.0.5
  Using cached python_multipart-0.0.5-py3-none-any.whl
Collecting numpy>=1.21
  Using cached numpy-1.21.2-cp37-cp37m-macosx_10_9_x86_64.whl (16.9 MB)
Collecting pint>=0.17
  Using cached Pint-0.17-py2.py3-none-any.whl (204 kB)
ERROR: Could not find a version that satisfies the requirement libroadrunner>=2.1.0 (from sbmlutils) (from versions: 1.5.2.1, 1.5.3, 1.5.4, 1.6.0, 1.6.0.1, 2.0.1, 2.0.3, 2.0.4, 2.0.5)
ERROR: No matching distribution found for libroadrunner>=2.1.0
```

**Comment by luciansmith** [comment]
Is the student running a MacOS version lower than 10.15?  Our automatic builds seem to be using Darwin.

**Comment by sankha555** [comment]
Yes, I am using 10.14. any workaround for that?

Thanks!

**Comment by luciansmith** [comment]
Looks like the answer is no--it seems that we switched to using 'std::filesystem::path' which was only introduced in MacOS 10.15  @CiaranWelsh : do you know of any MacOS 10.14 or earlier alternative to using std::filesystem::path?

**Comment by CiaranWelsh** [comment]
The problem isn't MacOS 10.14, its C++17. `std::filesystem::path` is a C++17 feature. The easiest thing to do would be to update your Mac. Its good to keep them up to date anyway! 

The newest roadrunner will work on macos 10.14 but we need to build roadrunner on this platform using the modern Clang compilers ( or at least C++17 compatible) and then upload the resulting pip wheel to pypi, along with the others. In the past we were not able to do this on azure because the only microsoft hosted agent was 10.15. However, I've just [noticed](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml) that they have recently added a macos 10.14 image that we can use. 

Just adding another branch to the pipeline isn't as straight forward as it seems however because we have a free subscription and our cloud resources are limited (we already sometimes hit an upper limit). If we add another OS to the build perhaps we should remove the Ubuntu, non-Python builds and maybe even support for Python 3.6 (3.7, 3.8 and 3.9 seem like enough to me).

**Comment by matthiaskoenig** [comment]
No worries. We removed libomexmeta and roadrunner from the respective project for now. Just opened this so others with the same issue get some hint. Not important to fix, we will try via a mac update.

**Comment by luciansmith** [comment]
In general, supporting three Pythons seems reasonable to me, though we should probably start testing 3.10 (which just released this month) in case we're using something deprecated, which would put us back at 4 again.

However, dropping the Ubuntu Python tests in favor of the manylinux2014 python tests seems like it wouldn't lose anything.

Adding a new MacOS 10.14 doesn't seem as helpful as just using 10.14 instead of 10.15, assuming everything is forward-compatible.

**Comment by hsauro** [comment]
Frank says Python 3.10 breaks things.

**Comment by luciansmith** [comment]
Yeah, all the more reason to start testing things early.

I did create a branch to test this, but it got stopped at the 'azure needs more stuff' level before it got to testing our actual code.  Python 3.10 doesn't exist for Conda yet (there was a bug having to do with '10' having two digits instead of one ;-) which we use for our linux and Windows builds, and on the mac, the 'ray' package isn't out yet, which it appears we depend on for something.  I'll keep an eye on it.

**Comment by matthiaskoenig** [comment]
Solved. Python 3.7 long out of date.
