### ISSUE TITLE
`roadrunner.roadrunner.Integrator.hasattr` raises KeyError rather than returning false

### ISSUE THREAD

**Issue by jonrkarr** [sys-bio/roadrunner#901]
This error is new. I believe to the 2.1.2 release.

Example
```
hasattr(mass_sim.integrator, 'x')
```

Raises a `KeyError` rather than the more conventional and previous behavior of returning false.

**Comment by luciansmith** [comment]
The issue turned out to be that __getattr__ must raise an AttributeError on failure, but was calling self.__dict__[name] directly instead of checking first.  (hasattr calls __getattr__ and checks for AttributeErrors).  Behavior had changed due to swig changing.

It is sort of obnoxious that __getattr__ must fail in a particular way to get hasattr to work properly, but I suppose that's what you get for modifying __ functions.

At any rate, this is now fixed in the roadrunner source.  Thank you for the report!
