### ISSUE TITLE
Roadrunner hangs on some Gillespie simulations

### ISSUE THREAD

**Issue by 0u812** [sys-bio/roadrunner#91]
I encountered this while trying to work through an exercise using the distrib package - I have a model with randomized initial assignments. Then, I simulate the model using the Gillespie integrator. About 1/3 of the time, the simulation simply hangs and I have to kill the process (does not respond to ctrl-C).

Model: http://chimicherry.mooo.com/hosted/gh-issues/rr/gillespie-hang/ant_poisson_model.py
Log of failed run (33 Mb), Level Debug: http://chimicherry.mooo.com/hosted/gh-issues/rr/gillespie-hang/rr.log.fail

**Comment by AndySomogyi** [comment]
The reason why this is getting stuck in a loop is because your initial conditions SET THE SPECIES AMOUNTS TO NEGATIVE VALUES!

So, the Gillespie integrator gets stuck in a loop as the next reaction is on the order of 10e-15 seconds, so it continuously runs this very small time step. 

I added a line to bail if the amounts are negative.

**Comment by AndySomogyi** [comment]
I check for negative concentrations in the integrator, and if they go negative, terminates the simulation. Resolved with 570ef7ba7277849e02a234e062e5af25be36522b
