### ISSUE TITLE
Rapid-Fire Random Number Bug

### ISSUE THREAD

**Issue by 0u812** [sys-bio/roadrunner#98]
Mike Hucka discovered an issue where RoadRunner produces repeated results when simulations are executed rapidly one after another (within 1 sec). Speculation: The random seed may be reinitialized each time the model is simulated. The fix would be to not do that, or else use a more high-res clock.

Background on model: It involves two events which fire at the same time. The SBML spec says such a race condition is resolved randomly, i.e. the "winning" event is selected at random.

**Comment by luciansmith** [comment]
This might not be an issue with roadrunner, but with the model.  Early on,
I had given Mike a model that fired when sin(time)>0, which is every 6.28
seconds.  He saw repeated time steps when the value had not changed, so
thought there was something going on, but in actual fact, it was simply
that the new randomized value wasn't being fired, since 6.28 seconds hadn't
passed yet.

I've run several models now that all repeatedly race events against each
other in roadrunner, and they all seem to work fine.  It's probably worth
looking into anyway, but I believe we'll find that there's no actual
problem.  At the very least, ask Mike for the model in question, if he
still thinks it's a roadrunner issue and not a model issue.

-Lucian

**Comment by hsauro** [comment]
There might be a configuration setting to change this behavior, check the docs though I am not sure of all the configuration options were documented.

H

**Comment by 0u812** [comment]
Cannot reproduce this behavior, and given @luciansmith's comment above I'm going to mark this as resolved. If anyone runs into this and can give me a working minimal example, please reopen.
